$kind: http-request
url: http://{{baseUrl}}/notify
method: POST
headers:
  Content-Type: application/json
  Accept: application/json
body:
  type: json
  content: ""
examples: ./.resources/Send a notification event to configured webhook
  targets.resources/examples
order: 1000
