name: AdGuard Dev
values:
  - key: dnsServerId
    value: 75b663d8
    enabled: true
  - key: baseUrl
    value: https://api.adguard-dns.io
    enabled: true
  - key: username
    value: ""
    enabled: true
  - key: password
    value: ""
    enabled: true
  - key: mfa_token
    value: ""
    enabled: true
  - key: apiKey
    value: ""
    enabled: true
color: null
