name: TopStep Prod
values:
  - key: authName
    value: trading@jaysonknight.com
    enabled: true
  - key: apiKey
    value: tIcurtwZ6oXzr6TC+2oe+YQUyhQRZ3DVTLGupwl7+Hg=
    enabled: true
  - key: bearerToken
    value: ""
    enabled: true
color: null
