[book]
title = "AdBlock Compiler"
authors = ["jaypatrick"]
src = "docs"

[output.html]
site-url = "/adblock-compiler/"
git-repository-url = "https://github.com/jaypatrick/adblock-compiler"
edit-url-template = "https://github.com/jaypatrick/adblock-compiler/edit/main/{path}"
additional-css = ["theme/custom.css"]
additional-js = ["theme/custom.js"]
