$kind: http-example
name: Query registration tasks assigned to account and pending tasks that are
  required for account approval
request:
  url: "{{baseUrl}}/gw/api/v1/accounts/:accountId/tasks?type=registration"
  method: GET
  headers:
    Accept: application/json
  queryParams:
    type: registration
  pathVariables:
    accountId: ""
response:
  statusCode: 200
  statusText: OK
  headers:
    Content-Type: application/json
  body:
    type: json
    content: >-
      {
        "error": {
          "error": {
            "value": "<Circular reference to #/components/schemas/ErrorResponse detected>"
          },
          "hasError": false,
          "errorDescription": "aute irure minim eu in"
        },
        "hasError": false,
        "errorDescription": "esse culpa enim fugiat",
        "accountId": "proident esse",
        "status": "dolore culpa minim",
        "description": "id amet",
        "state": "fugiat deserunt dolore",
        "registrationTaskPresent": true,
        "registrationTasks": [
          {
            "externalId": "nulla nostrud est",
            "formName": "esse",
            "action": "nostrud do adipisicing dolor in",
            "isRequiredForApproval": false,
            "isCompleted": true,
            "dateCompleted": "1963-10-30T10:06:55.155Z",
            "state": "laboris sint exercitati"
          },
          {
            "externalId": "eiusmod exercitation veniam elit",
            "formName": "in ex culpa",
            "action": "sit ullamco in laboris",
            "isRequiredForApproval": true,
            "isCompleted": true,
            "dateCompleted": "2010-01-27T05:17:57.824Z",
            "state": "reprehenderit aliquip"
          }
        ]
      }
order: 9000
