/**
 * Unified Authentication Middleware
 *
 * Authenticates requests via a three-tier chain:
 *   1. **Clerk JWT** — Bearer token verified against Clerk JWKS (primary)
 *   2. **API key** — Bearer token with `abc_` prefix, hashed & looked up in PostgreSQL
 *   3. **Anonymous** — No credentials; falls through to anonymous context
 *
 * Token disambiguation:
 *   - API keys always start with `abc_` (generated by api-key-utils.ts)
 *   - Clerk JWTs are dot-separated base64 strings (header.payload.signature)
 *   - If a Bearer token matches neither pattern, it is rejected
 *
 * Legacy support:
 *   - `authenticateApiKey()` and `authenticateRequest()` are preserved for
 *     backward compatibility but should be migrated to `authenticateRequestUnified()`.
 *
 * @see worker/middleware/clerk-jwt.ts — JWT verification
 * @see worker/types.ts — IAuthContext, IAuthMiddlewareResult, UserTier
 */

import type { Env, HyperdriveBinding } from '../types.ts';
import {
    type IAuthContext,
    type IAuthMiddlewareResult,
    type IClerkPublicMetadata,
    UserTier,
    ANONYMOUS_AUTH_CONTEXT,
} from '../types.ts';
import { verifyClerkJWT } from './clerk-jwt.ts';

// ============================================================================
// Types
// ============================================================================

/**
 * Result of API key authentication.
 */
export interface ApiKeyAuthResult {
    authenticated: boolean;
    userId?: string;
    apiKeyId?: string;
    scopes?: string[];
    error?: string;
}

/**
 * Authenticated request context attached after successful auth.
 */
export interface AuthContext {
    userId: string;
    apiKeyId: string;
    scopes: string[];
}

/**
 * Minimal pg Pool interface for auth queries.
 */
interface PgPool {
    query<T = Record<string, unknown>>(text: string, values?: unknown[]): Promise<{ rows: T[]; rowCount: number | null }>;
}

/**
 * Factory to create a pg Pool from a connection string.
 */
export type PgPoolFactory = (connectionString: string) => PgPool;

// ============================================================================
// Token Hashing
// ============================================================================

/**
 * Hashes an API key token using SHA-256.
 * Uses the Web Crypto API available in Cloudflare Workers.
 */
async function hashToken(token: string): Promise<string> {
    const encoder = new TextEncoder();
    const data = encoder.encode(token);
    const hashBuffer = await crypto.subtle.digest('SHA-256', data);
    const hashArray = Array.from(new Uint8Array(hashBuffer));
    return hashArray.map((b) => b.toString(16).padStart(2, '0')).join('');
}

/**
 * Extracts Bearer token from the Authorization header.
 * Returns null if no valid Bearer token is present.
 */
function extractBearerToken(request: Request): string | null {
    const authHeader = request.headers.get('Authorization');
    if (!authHeader) return null;

    const parts = authHeader.split(' ');
    if (parts.length !== 2 || parts[0].toLowerCase() !== 'bearer') return null;

    const token = parts[1].trim();
    return token.length > 0 ? token : null;
}

// ============================================================================
// Authentication
// ============================================================================

/**
 * Authenticates a request using an API key stored in PostgreSQL.
 *
 * @param request - Incoming HTTP request
 * @param hyperdrive - Cloudflare Hyperdrive binding
 * @param createPool - Factory to create a pg Pool
 * @param requiredScope - Scope the API key must have (e.g., 'compile', 'admin')
 * @returns Authentication result with user context
 *
 * @example
 * ```typescript
 * const auth = await authenticateApiKey(request, env.HYPERDRIVE, poolFactory, 'compile');
 * if (!auth.authenticated) {
 *     return JsonResponse.error(auth.error, 401);
 * }
 * // auth.userId, auth.apiKeyId, auth.scopes are available
 * ```
 */
export async function authenticateApiKey(
    request: Request,
    hyperdrive: HyperdriveBinding,
    createPool: PgPoolFactory,
    requiredScope?: string,
): Promise<ApiKeyAuthResult> {
    const token = extractBearerToken(request);
    if (!token) {
        return { authenticated: false, error: 'Missing or invalid Authorization header. Use: Bearer <api-key>' };
    }

    const keyHash = await hashToken(token);
    const pool = createPool(hyperdrive.connectionString);

    try {
        const result = await pool.query<{
            id: string;
            user_id: string;
            scopes: string[];
            rate_limit_per_minute: number;
            expires_at: string | null;
            revoked_at: string | null;
        }>(
            `SELECT id, user_id, scopes, rate_limit_per_minute, expires_at, revoked_at
             FROM api_keys
             WHERE key_hash = $1`,
            [keyHash],
        );

        if (result.rows.length === 0) {
            return { authenticated: false, error: 'Invalid API key' };
        }

        const apiKey = result.rows[0];

        // Check if revoked
        if (apiKey.revoked_at) {
            return { authenticated: false, error: 'API key has been revoked' };
        }

        // Check if expired
        if (apiKey.expires_at && new Date(apiKey.expires_at) < new Date()) {
            return { authenticated: false, error: 'API key has expired' };
        }

        // Check scope
        if (requiredScope && !apiKey.scopes.includes(requiredScope)) {
            return {
                authenticated: false,
                error: `API key missing required scope: ${requiredScope}`,
            };
        }

        // Update last_used_at (fire-and-forget, don't block the response)
        pool.query(
            `UPDATE api_keys SET last_used_at = NOW() WHERE id = $1`,
            [apiKey.id],
        ).catch(() => {/* intentional: non-critical update */});

        return {
            authenticated: true,
            userId: apiKey.user_id,
            apiKeyId: apiKey.id,
            scopes: apiKey.scopes,
        };
    } catch (error) {
        const message = error instanceof Error ? error.message : String(error);
        return { authenticated: false, error: `Authentication service error: ${message}` };
    }
}

/**
 * Combined auth check: tries API key auth via Hyperdrive first,
 * falls back to static ADMIN_KEY for backward compatibility.
 *
 * Use this for admin routes during the migration period.
 *
 * @param request - Incoming HTTP request
 * @param env - Partial env with ADMIN_KEY and optional HYPERDRIVE
 * @param createPool - Optional pg Pool factory (required if HYPERDRIVE is set)
 * @returns Authentication result
 */
export async function authenticateRequest(
    request: Request,
    env: { ADMIN_KEY?: string; HYPERDRIVE?: HyperdriveBinding },
    createPool?: PgPoolFactory,
): Promise<ApiKeyAuthResult> {
    // Try API key auth if Hyperdrive is available
    const token = extractBearerToken(request);
    if (token && env.HYPERDRIVE && createPool) {
        return authenticateApiKey(request, env.HYPERDRIVE, createPool, 'admin');
    }

    // Fall back to static ADMIN_KEY
    const adminKey = request.headers.get('X-Admin-Key');
    if (!env.ADMIN_KEY) {
        return { authenticated: false, error: 'Authentication not configured' };
    }
    if (!adminKey || adminKey !== env.ADMIN_KEY) {
        return { authenticated: false, error: 'Unauthorized' };
    }

    return { authenticated: true };
}

// ---------------------------------------------------------------------------
// Unified Authentication (Clerk JWT → API Key → Anonymous)
// ---------------------------------------------------------------------------

/** Check whether a Bearer token looks like an API key (abc_ prefix). */
function isApiKeyToken(token: string): boolean {
    return token.startsWith('abc_');
}

/** Check whether a Bearer token looks like a JWT (three dot-separated segments). */
function isJwtToken(token: string): boolean {
    const parts = token.split('.');
    return parts.length === 3 && parts.every((p) => p.length > 0);
}

/**
 * Map Clerk public metadata to a {@link UserTier}.
 *
 * Clerk users store their tier in `publicMetadata.tier` as a {@link UserTier}
 * enum value. If the value is missing the user defaults to {@link UserTier.Free}.
 */
function resolveTierFromMetadata(metadata: IClerkPublicMetadata | undefined): UserTier {
    if (!metadata?.tier) return UserTier.Free;
    return metadata.tier;
}

/**
 * Map Clerk public metadata to a role string.
 *
 * Falls back to `'user'` when the metadata does not specify a role.
 */
function resolveRoleFromMetadata(metadata: IClerkPublicMetadata | undefined): string {
    return metadata?.role ?? 'user';
}

/**
 * Authenticate a request using the unified three-tier chain.
 *
 * The chain tries, **in order**:
 *
 * 1. **Clerk JWT** — If the Bearer token is a JWT (contains dots, not an
 *    `abc_` key) it is verified against the Clerk JWKS endpoint. On success
 *    the user's tier and role are read from the JWT's public metadata claims.
 *
 * 2. **API key** — If the Bearer token starts with `abc_` it is hashed and
 *    looked up in PostgreSQL via Hyperdrive. The authenticated user inherits
 *    the tier associated with the key's owner.
 *
 * 3. **Anonymous** — When no credentials are present the request proceeds as
 *    {@link ANONYMOUS_AUTH_CONTEXT} (10 req/min rate limit, basic features).
 *
 * The function **never throws**. Auth failures are signalled via the optional
 * `response` field on the result — callers should check for a `response` and
 * short-circuit the request when present.
 *
 * @param request    - Incoming HTTP request
 * @param env        - Worker env bindings (must include Clerk + optional Hyperdrive vars)
 * @param createPool - Optional pg Pool factory for API key lookups
 * @returns A {@link IAuthMiddlewareResult} with the resolved auth context
 */
export async function authenticateRequestUnified(
    request: Request,
    env: Env,
    createPool?: PgPoolFactory,
): Promise<IAuthMiddlewareResult> {
    const token = extractBearerToken(request);

    // --- No token → anonymous ---
    if (!token) {
        return { context: { ...ANONYMOUS_AUTH_CONTEXT } };
    }

    // --- API key path ---
    if (isApiKeyToken(token)) {
        if (!env.HYPERDRIVE || !createPool) {
            return {
                context: { ...ANONYMOUS_AUTH_CONTEXT },
                response: new Response(
                    JSON.stringify({ error: 'API key authentication is not configured' }),
                    { status: 503, headers: { 'Content-Type': 'application/json' } },
                ),
            };
        }

        const result = await authenticateApiKey(request, env.HYPERDRIVE, createPool);
        if (result.authenticated) {
            const context: IAuthContext = {
                userId: result.userId ?? null,
                clerkUserId: null,
                tier: UserTier.Free, // TODO(@jaypatrick): look up tier from user record
                role: 'user',
                apiKeyId: result.apiKeyId ?? null,
                sessionId: null,
                scopes: result.scopes ?? [],
                authMethod: 'api-key',
            };
            return { context };
        }

        return {
            context: { ...ANONYMOUS_AUTH_CONTEXT },
            response: new Response(
                JSON.stringify({ error: result.error ?? 'Invalid API key' }),
                { status: 401, headers: { 'Content-Type': 'application/json' } },
            ),
        };
    }

    // --- JWT path ---
    if (isJwtToken(token)) {
        const jwtResult = await verifyClerkJWT(request, env);

        if (jwtResult.valid && jwtResult.claims) {
            const metadata = jwtResult.claims.metadata;
            const context: IAuthContext = {
                userId: null, // TODO(@jaypatrick): resolve DB userId from clerkUserId
                clerkUserId: jwtResult.claims.sub,
                tier: resolveTierFromMetadata(metadata),
                role: resolveRoleFromMetadata(metadata),
                apiKeyId: null,
                sessionId: jwtResult.claims.sid ?? null,
                scopes: [],
                authMethod: 'clerk-jwt',
            };
            return { context };
        }

        return {
            context: { ...ANONYMOUS_AUTH_CONTEXT },
            response: new Response(
                JSON.stringify({ error: jwtResult.error ?? 'Invalid JWT' }),
                { status: 401, headers: { 'Content-Type': 'application/json' } },
            ),
        };
    }

    // --- Unrecognised token format ---
    return {
        context: { ...ANONYMOUS_AUTH_CONTEXT },
        response: new Response(
            JSON.stringify({ error: 'Unrecognised credential format — expected a Clerk JWT or abc_-prefixed API key' }),
            { status: 401, headers: { 'Content-Type': 'application/json' } },
        ),
    };
}
