$kind: http-example
request:
  url: {{baseUrl}}/api/deployments/stats
  method: GET
  headers:
    Accept: application/json
  body:
    type: text
    content: ""
response:
  statusCode: 503
  statusText: Service Unavailable
  headers:
    Content-Type: application/json
  body:
    type: json
    content: |-
      {
        "success": false,
        "error": "string"
      }
order: 2000
