$kind: http-example
name: >
  Internal Server Error. Unable to process request if incoming values are not
  valid. For example accountId is not correct
request:
  url: "{{baseUrl}}/iserver/account"
  method: POST
  headers:
    Content-Type: application/json
    Accept: application/json
  body:
    type: json
    content: |-
      {
        "acctId": "U1234567"
      }
response:
  statusCode: 500
  statusText: Internal Server Error
  headers:
    Content-Type: application/json
  body:
    type: json
    content: |-
      {
        "error": "Invalid account ID"
      }
order: 5000
