$kind: collection
description: Collection for testing Unifi Network API (UNA) Endpoints
variables:
  remote-base-url: api.ui.com
  https: https://
  ea: ea
  hosts: hosts
  api-key-remote: 3wGLEhKuo243R40mUMhQYj7mZqb0M80g
  api-key-local: xbtpA1tAietowYGMXi_8PJ-L8okpTlFd
  local-base-url: unifi.jaysonknight.com
  local-base-ip: 192.168.1.140
  sites: sites
  version: v1
  integration: integration
  network: network
  proxy: proxy
  http: http://
  clients: clients
  site-id: ""
  host-id: ""
  devices: devices
  info: info
  device-id: ""
  statistics: statistics
  latest: latest
