$kind: http-example
request:
  url: "{{baseUrl}}/oapi/v1/dns_servers/:dns_server_id/settings"
  method: PUT
  headers:
    - key: Content-Type
      value: application/json
    - key: Authorization
      value: Bearer <token>
      description: "Added as a part of security scheme: bearer"
  pathVariables:
    dns_server_id: ""
  body:
    type: json
    content: |-
      {
        "access_settings": {
          "allowed_clients": [
            "<string>",
            "<string>"
          ],
          "block_known_scanners": "<boolean>",
          "blocked_clients": [
            "<string>",
            "<string>"
          ],
          "blocked_domain_rules": [
            "<string>",
            "<string>"
          ],
          "enabled": "<boolean>"
        },
        "auto_connect_devices_enabled": "<boolean>",
        "block_chrome_prefetch": "<boolean>",
        "block_firefox_canary": "<boolean>",
        "block_private_relay": "<boolean>",
        "block_ttl_seconds": "<integer>",
        "blocking_mode_settings": {
          "blocking_mode": "CUSTOM_IP",
          "ipv4_blocking_address": "<string>",
          "ipv6_blocking_address": "<string>"
        },
        "filter_lists_settings": {
          "enabled": "<boolean>",
          "filter_list": [
            {
              "filter_id": "<string>",
              "enabled": "<boolean>"
            },
            {
              "filter_id": "<string>",
              "enabled": "<boolean>"
            }
          ]
        },
        "ip_log_enabled": "<boolean>",
        "parental_control_settings": {
          "block_adult_websites_enabled": "<boolean>",
          "blocked_services": [
            {
              "id": "<string>",
              "enabled": "<boolean>"
            },
            {
              "id": "<string>",
              "enabled": "<boolean>"
            }
          ],
          "enabled": "<boolean>",
          "engines_safe_search_enabled": "<boolean>",
          "screen_time_schedule": {
            "daily_schedule": [
              {
                "day_of_week": "TUESDAY",
                "enabled": "<boolean>",
                "from_time": {
                  "hours": "<integer>",
                  "minutes": "<integer>"
                },
                "to_time": {
                  "hours": "<integer>",
                  "minutes": "<integer>"
                }
              },
              {
                "day_of_week": "MONDAY",
                "enabled": "<boolean>",
                "from_time": {
                  "hours": "<integer>",
                  "minutes": "<integer>"
                },
                "to_time": {
                  "hours": "<integer>",
                  "minutes": "<integer>"
                }
              }
            ]
          },
          "youtube_safe_search_enabled": "<boolean>"
        },
        "protection_enabled": "<boolean>",
        "safebrowsing_settings": {
          "block_dangerous_domains": "<boolean>",
          "block_nrd": "<boolean>",
          "enabled": "<boolean>"
        },
        "user_rules_settings": {
          "enabled": "<boolean>",
          "rules": [
            "<string>",
            "<string>"
          ]
        }
      }
response:
  statusCode: 200
  statusText: OK
  body:
    type: text
    content: ""
order: 1000
