
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models.js'
export type * from './prismaNamespace.js'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  User: 'User',
  StorageEntry: 'StorageEntry',
  FilterCache: 'FilterCache',
  CompilationMetadata: 'CompilationMetadata',
  SourceSnapshot: 'SourceSnapshot',
  SourceHealth: 'SourceHealth',
  SourceAttempt: 'SourceAttempt'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UserScalarFieldEnum = {
  id: 'id',
  email: 'email',
  displayName: 'displayName',
  role: 'role',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  clerkUserId: 'clerkUserId',
  tier: 'tier',
  firstName: 'firstName',
  lastName: 'lastName',
  imageUrl: 'imageUrl',
  emailVerified: 'emailVerified',
  lastSignInAt: 'lastSignInAt'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const StorageEntryScalarFieldEnum = {
  id: 'id',
  key: 'key',
  data: 'data',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  expiresAt: 'expiresAt',
  tags: 'tags'
} as const

export type StorageEntryScalarFieldEnum = (typeof StorageEntryScalarFieldEnum)[keyof typeof StorageEntryScalarFieldEnum]


export const FilterCacheScalarFieldEnum = {
  id: 'id',
  source: 'source',
  content: 'content',
  hash: 'hash',
  etag: 'etag',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  expiresAt: 'expiresAt'
} as const

export type FilterCacheScalarFieldEnum = (typeof FilterCacheScalarFieldEnum)[keyof typeof FilterCacheScalarFieldEnum]


export const CompilationMetadataScalarFieldEnum = {
  id: 'id',
  configName: 'configName',
  timestamp: 'timestamp',
  sourceCount: 'sourceCount',
  ruleCount: 'ruleCount',
  duration: 'duration',
  outputPath: 'outputPath'
} as const

export type CompilationMetadataScalarFieldEnum = (typeof CompilationMetadataScalarFieldEnum)[keyof typeof CompilationMetadataScalarFieldEnum]


export const SourceSnapshotScalarFieldEnum = {
  id: 'id',
  source: 'source',
  timestamp: 'timestamp',
  contentHash: 'contentHash',
  ruleCount: 'ruleCount',
  ruleSample: 'ruleSample',
  etag: 'etag',
  isCurrent: 'isCurrent'
} as const

export type SourceSnapshotScalarFieldEnum = (typeof SourceSnapshotScalarFieldEnum)[keyof typeof SourceSnapshotScalarFieldEnum]


export const SourceHealthScalarFieldEnum = {
  id: 'id',
  source: 'source',
  status: 'status',
  totalAttempts: 'totalAttempts',
  successfulAttempts: 'successfulAttempts',
  failedAttempts: 'failedAttempts',
  consecutiveFailures: 'consecutiveFailures',
  averageDuration: 'averageDuration',
  averageRuleCount: 'averageRuleCount',
  lastAttemptAt: 'lastAttemptAt',
  lastSuccessAt: 'lastSuccessAt',
  lastFailureAt: 'lastFailureAt',
  recentAttempts: 'recentAttempts',
  updatedAt: 'updatedAt'
} as const

export type SourceHealthScalarFieldEnum = (typeof SourceHealthScalarFieldEnum)[keyof typeof SourceHealthScalarFieldEnum]


export const SourceAttemptScalarFieldEnum = {
  id: 'id',
  source: 'source',
  timestamp: 'timestamp',
  success: 'success',
  duration: 'duration',
  error: 'error',
  ruleCount: 'ruleCount',
  etag: 'etag'
} as const

export type SourceAttemptScalarFieldEnum = (typeof SourceAttemptScalarFieldEnum)[keyof typeof SourceAttemptScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

