$kind: http-request
url: "{{baseUrl}}/api/turnstile-config"
method: GET
scripts:
  - type: afterResponse
    code: |-
      pm.test("Status code is 200", function () {
          pm.response.to.have.status(200);
      });

      pm.test("Response is JSON", function () {
          pm.response.to.be.json;
      });

      pm.test("Response has turnstile config", function () {
          const jsonData = pm.response.json();
          pm.expect(jsonData).to.have.property("enabled");
      });
    language: text/javascript
order: 6000
