$kind: http-example
request:
  url: http://{{baseUrl}}/workflow/batch
  method: POST
  headers:
    Content-Type: application/json
    Accept: application/json
  body:
    type: json
    content: >-
      {
        "requests": [
          {
            "id": "string",
            "configuration": {
              "name": "string",
              "sources": [
                {
                  "source": "string",
                  "name": "string",
                  "type": "adblock",
                  "transformations": [
                    "Deduplicate",
                    "Validate"
                  ],
                  "exclusions": [
                    "string",
                    "string"
                  ],
                  "inclusions": [
                    "string",
                    "string"
                  ]
                }
              ],
              "description": "string",
              "homepage": "http://HiyzupPqRUMJatjQUvaAc.kfB,nhSEdU5jPu+9D4.7tD1S+YIwehzyGyJ.4yNOR2Mj4qih",
              "license": "string",
              "version": "string",
              "transformations": [
                "RemoveComments",
                "Validate"
              ],
              "exclusions": [
                "string",
                "string"
              ],
              "exclusions_sources": [
                "string",
                "string"
              ],
              "inclusions": [
                "string",
                "string"
              ],
              "inclusions_sources": [
                "string",
                "string"
              ]
            },
            "preFetchedContent": {
              "key_0": "string"
            },
            "benchmark": true
          }
        ]
      }
response:
  statusCode: 503
  statusText: Service Unavailable
  headers:
    Content-Type: application/json
  body:
    type: json
    content: |-
      {
        "success": false,
        "error": "string"
      }
order: 3000
