
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `FilterCache` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model FilterCache
 * 
 */
export type FilterCacheModel = runtime.Types.Result.DefaultSelection<Prisma.$FilterCachePayload>

export type AggregateFilterCache = {
  _count: FilterCacheCountAggregateOutputType | null
  _min: FilterCacheMinAggregateOutputType | null
  _max: FilterCacheMaxAggregateOutputType | null
}

export type FilterCacheMinAggregateOutputType = {
  id: string | null
  source: string | null
  content: string | null
  hash: string | null
  etag: string | null
  createdAt: Date | null
  updatedAt: Date | null
  expiresAt: Date | null
}

export type FilterCacheMaxAggregateOutputType = {
  id: string | null
  source: string | null
  content: string | null
  hash: string | null
  etag: string | null
  createdAt: Date | null
  updatedAt: Date | null
  expiresAt: Date | null
}

export type FilterCacheCountAggregateOutputType = {
  id: number
  source: number
  content: number
  hash: number
  etag: number
  createdAt: number
  updatedAt: number
  expiresAt: number
  _all: number
}


export type FilterCacheMinAggregateInputType = {
  id?: true
  source?: true
  content?: true
  hash?: true
  etag?: true
  createdAt?: true
  updatedAt?: true
  expiresAt?: true
}

export type FilterCacheMaxAggregateInputType = {
  id?: true
  source?: true
  content?: true
  hash?: true
  etag?: true
  createdAt?: true
  updatedAt?: true
  expiresAt?: true
}

export type FilterCacheCountAggregateInputType = {
  id?: true
  source?: true
  content?: true
  hash?: true
  etag?: true
  createdAt?: true
  updatedAt?: true
  expiresAt?: true
  _all?: true
}

export type FilterCacheAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which FilterCache to aggregate.
   */
  where?: Prisma.FilterCacheWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FilterCaches to fetch.
   */
  orderBy?: Prisma.FilterCacheOrderByWithRelationInput | Prisma.FilterCacheOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.FilterCacheWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FilterCaches from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FilterCaches.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned FilterCaches
  **/
  _count?: true | FilterCacheCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: FilterCacheMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: FilterCacheMaxAggregateInputType
}

export type GetFilterCacheAggregateType<T extends FilterCacheAggregateArgs> = {
      [P in keyof T & keyof AggregateFilterCache]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateFilterCache[P]>
    : Prisma.GetScalarType<T[P], AggregateFilterCache[P]>
}




export type FilterCacheGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FilterCacheWhereInput
  orderBy?: Prisma.FilterCacheOrderByWithAggregationInput | Prisma.FilterCacheOrderByWithAggregationInput[]
  by: Prisma.FilterCacheScalarFieldEnum[] | Prisma.FilterCacheScalarFieldEnum
  having?: Prisma.FilterCacheScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: FilterCacheCountAggregateInputType | true
  _min?: FilterCacheMinAggregateInputType
  _max?: FilterCacheMaxAggregateInputType
}

export type FilterCacheGroupByOutputType = {
  id: string
  source: string
  content: string
  hash: string
  etag: string | null
  createdAt: Date
  updatedAt: Date
  expiresAt: Date | null
  _count: FilterCacheCountAggregateOutputType | null
  _min: FilterCacheMinAggregateOutputType | null
  _max: FilterCacheMaxAggregateOutputType | null
}

type GetFilterCacheGroupByPayload<T extends FilterCacheGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<FilterCacheGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof FilterCacheGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], FilterCacheGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], FilterCacheGroupByOutputType[P]>
      }
    >
  >



export type FilterCacheWhereInput = {
  AND?: Prisma.FilterCacheWhereInput | Prisma.FilterCacheWhereInput[]
  OR?: Prisma.FilterCacheWhereInput[]
  NOT?: Prisma.FilterCacheWhereInput | Prisma.FilterCacheWhereInput[]
  id?: Prisma.StringFilter<"FilterCache"> | string
  source?: Prisma.StringFilter<"FilterCache"> | string
  content?: Prisma.StringFilter<"FilterCache"> | string
  hash?: Prisma.StringFilter<"FilterCache"> | string
  etag?: Prisma.StringNullableFilter<"FilterCache"> | string | null
  createdAt?: Prisma.DateTimeFilter<"FilterCache"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"FilterCache"> | Date | string
  expiresAt?: Prisma.DateTimeNullableFilter<"FilterCache"> | Date | string | null
}

export type FilterCacheOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  source?: Prisma.SortOrder
  content?: Prisma.SortOrder
  hash?: Prisma.SortOrder
  etag?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrderInput | Prisma.SortOrder
}

export type FilterCacheWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  source?: string
  AND?: Prisma.FilterCacheWhereInput | Prisma.FilterCacheWhereInput[]
  OR?: Prisma.FilterCacheWhereInput[]
  NOT?: Prisma.FilterCacheWhereInput | Prisma.FilterCacheWhereInput[]
  content?: Prisma.StringFilter<"FilterCache"> | string
  hash?: Prisma.StringFilter<"FilterCache"> | string
  etag?: Prisma.StringNullableFilter<"FilterCache"> | string | null
  createdAt?: Prisma.DateTimeFilter<"FilterCache"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"FilterCache"> | Date | string
  expiresAt?: Prisma.DateTimeNullableFilter<"FilterCache"> | Date | string | null
}, "id" | "source">

export type FilterCacheOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  source?: Prisma.SortOrder
  content?: Prisma.SortOrder
  hash?: Prisma.SortOrder
  etag?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.FilterCacheCountOrderByAggregateInput
  _max?: Prisma.FilterCacheMaxOrderByAggregateInput
  _min?: Prisma.FilterCacheMinOrderByAggregateInput
}

export type FilterCacheScalarWhereWithAggregatesInput = {
  AND?: Prisma.FilterCacheScalarWhereWithAggregatesInput | Prisma.FilterCacheScalarWhereWithAggregatesInput[]
  OR?: Prisma.FilterCacheScalarWhereWithAggregatesInput[]
  NOT?: Prisma.FilterCacheScalarWhereWithAggregatesInput | Prisma.FilterCacheScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"FilterCache"> | string
  source?: Prisma.StringWithAggregatesFilter<"FilterCache"> | string
  content?: Prisma.StringWithAggregatesFilter<"FilterCache"> | string
  hash?: Prisma.StringWithAggregatesFilter<"FilterCache"> | string
  etag?: Prisma.StringNullableWithAggregatesFilter<"FilterCache"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"FilterCache"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"FilterCache"> | Date | string
  expiresAt?: Prisma.DateTimeNullableWithAggregatesFilter<"FilterCache"> | Date | string | null
}

export type FilterCacheCreateInput = {
  id?: string
  source: string
  content: string
  hash: string
  etag?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  expiresAt?: Date | string | null
}

export type FilterCacheUncheckedCreateInput = {
  id?: string
  source: string
  content: string
  hash: string
  etag?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  expiresAt?: Date | string | null
}

export type FilterCacheUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  source?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  hash?: Prisma.StringFieldUpdateOperationsInput | string
  etag?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type FilterCacheUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  source?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  hash?: Prisma.StringFieldUpdateOperationsInput | string
  etag?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type FilterCacheCreateManyInput = {
  id?: string
  source: string
  content: string
  hash: string
  etag?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  expiresAt?: Date | string | null
}

export type FilterCacheUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  source?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  hash?: Prisma.StringFieldUpdateOperationsInput | string
  etag?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type FilterCacheUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  source?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  hash?: Prisma.StringFieldUpdateOperationsInput | string
  etag?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type FilterCacheCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  source?: Prisma.SortOrder
  content?: Prisma.SortOrder
  hash?: Prisma.SortOrder
  etag?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
}

export type FilterCacheMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  source?: Prisma.SortOrder
  content?: Prisma.SortOrder
  hash?: Prisma.SortOrder
  etag?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
}

export type FilterCacheMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  source?: Prisma.SortOrder
  content?: Prisma.SortOrder
  hash?: Prisma.SortOrder
  etag?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
}



export type FilterCacheSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  source?: boolean
  content?: boolean
  hash?: boolean
  etag?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  expiresAt?: boolean
}, ExtArgs["result"]["filterCache"]>

export type FilterCacheSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  source?: boolean
  content?: boolean
  hash?: boolean
  etag?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  expiresAt?: boolean
}, ExtArgs["result"]["filterCache"]>

export type FilterCacheSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  source?: boolean
  content?: boolean
  hash?: boolean
  etag?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  expiresAt?: boolean
}, ExtArgs["result"]["filterCache"]>

export type FilterCacheSelectScalar = {
  id?: boolean
  source?: boolean
  content?: boolean
  hash?: boolean
  etag?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  expiresAt?: boolean
}

export type FilterCacheOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "source" | "content" | "hash" | "etag" | "createdAt" | "updatedAt" | "expiresAt", ExtArgs["result"]["filterCache"]>

export type $FilterCachePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "FilterCache"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    source: string
    content: string
    hash: string
    etag: string | null
    createdAt: Date
    updatedAt: Date
    expiresAt: Date | null
  }, ExtArgs["result"]["filterCache"]>
  composites: {}
}

export type FilterCacheGetPayload<S extends boolean | null | undefined | FilterCacheDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$FilterCachePayload, S>

export type FilterCacheCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<FilterCacheFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: FilterCacheCountAggregateInputType | true
  }

export interface FilterCacheDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['FilterCache'], meta: { name: 'FilterCache' } }
  /**
   * Find zero or one FilterCache that matches the filter.
   * @param {FilterCacheFindUniqueArgs} args - Arguments to find a FilterCache
   * @example
   * // Get one FilterCache
   * const filterCache = await prisma.filterCache.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends FilterCacheFindUniqueArgs>(args: Prisma.SelectSubset<T, FilterCacheFindUniqueArgs<ExtArgs>>): Prisma.Prisma__FilterCacheClient<runtime.Types.Result.GetResult<Prisma.$FilterCachePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one FilterCache that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {FilterCacheFindUniqueOrThrowArgs} args - Arguments to find a FilterCache
   * @example
   * // Get one FilterCache
   * const filterCache = await prisma.filterCache.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends FilterCacheFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, FilterCacheFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__FilterCacheClient<runtime.Types.Result.GetResult<Prisma.$FilterCachePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first FilterCache that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FilterCacheFindFirstArgs} args - Arguments to find a FilterCache
   * @example
   * // Get one FilterCache
   * const filterCache = await prisma.filterCache.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends FilterCacheFindFirstArgs>(args?: Prisma.SelectSubset<T, FilterCacheFindFirstArgs<ExtArgs>>): Prisma.Prisma__FilterCacheClient<runtime.Types.Result.GetResult<Prisma.$FilterCachePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first FilterCache that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FilterCacheFindFirstOrThrowArgs} args - Arguments to find a FilterCache
   * @example
   * // Get one FilterCache
   * const filterCache = await prisma.filterCache.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends FilterCacheFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, FilterCacheFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__FilterCacheClient<runtime.Types.Result.GetResult<Prisma.$FilterCachePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more FilterCaches that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FilterCacheFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all FilterCaches
   * const filterCaches = await prisma.filterCache.findMany()
   * 
   * // Get first 10 FilterCaches
   * const filterCaches = await prisma.filterCache.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const filterCacheWithIdOnly = await prisma.filterCache.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends FilterCacheFindManyArgs>(args?: Prisma.SelectSubset<T, FilterCacheFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FilterCachePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a FilterCache.
   * @param {FilterCacheCreateArgs} args - Arguments to create a FilterCache.
   * @example
   * // Create one FilterCache
   * const FilterCache = await prisma.filterCache.create({
   *   data: {
   *     // ... data to create a FilterCache
   *   }
   * })
   * 
   */
  create<T extends FilterCacheCreateArgs>(args: Prisma.SelectSubset<T, FilterCacheCreateArgs<ExtArgs>>): Prisma.Prisma__FilterCacheClient<runtime.Types.Result.GetResult<Prisma.$FilterCachePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many FilterCaches.
   * @param {FilterCacheCreateManyArgs} args - Arguments to create many FilterCaches.
   * @example
   * // Create many FilterCaches
   * const filterCache = await prisma.filterCache.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends FilterCacheCreateManyArgs>(args?: Prisma.SelectSubset<T, FilterCacheCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many FilterCaches and returns the data saved in the database.
   * @param {FilterCacheCreateManyAndReturnArgs} args - Arguments to create many FilterCaches.
   * @example
   * // Create many FilterCaches
   * const filterCache = await prisma.filterCache.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many FilterCaches and only return the `id`
   * const filterCacheWithIdOnly = await prisma.filterCache.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends FilterCacheCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, FilterCacheCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FilterCachePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a FilterCache.
   * @param {FilterCacheDeleteArgs} args - Arguments to delete one FilterCache.
   * @example
   * // Delete one FilterCache
   * const FilterCache = await prisma.filterCache.delete({
   *   where: {
   *     // ... filter to delete one FilterCache
   *   }
   * })
   * 
   */
  delete<T extends FilterCacheDeleteArgs>(args: Prisma.SelectSubset<T, FilterCacheDeleteArgs<ExtArgs>>): Prisma.Prisma__FilterCacheClient<runtime.Types.Result.GetResult<Prisma.$FilterCachePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one FilterCache.
   * @param {FilterCacheUpdateArgs} args - Arguments to update one FilterCache.
   * @example
   * // Update one FilterCache
   * const filterCache = await prisma.filterCache.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends FilterCacheUpdateArgs>(args: Prisma.SelectSubset<T, FilterCacheUpdateArgs<ExtArgs>>): Prisma.Prisma__FilterCacheClient<runtime.Types.Result.GetResult<Prisma.$FilterCachePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more FilterCaches.
   * @param {FilterCacheDeleteManyArgs} args - Arguments to filter FilterCaches to delete.
   * @example
   * // Delete a few FilterCaches
   * const { count } = await prisma.filterCache.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends FilterCacheDeleteManyArgs>(args?: Prisma.SelectSubset<T, FilterCacheDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more FilterCaches.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FilterCacheUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many FilterCaches
   * const filterCache = await prisma.filterCache.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends FilterCacheUpdateManyArgs>(args: Prisma.SelectSubset<T, FilterCacheUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more FilterCaches and returns the data updated in the database.
   * @param {FilterCacheUpdateManyAndReturnArgs} args - Arguments to update many FilterCaches.
   * @example
   * // Update many FilterCaches
   * const filterCache = await prisma.filterCache.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more FilterCaches and only return the `id`
   * const filterCacheWithIdOnly = await prisma.filterCache.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends FilterCacheUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, FilterCacheUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FilterCachePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one FilterCache.
   * @param {FilterCacheUpsertArgs} args - Arguments to update or create a FilterCache.
   * @example
   * // Update or create a FilterCache
   * const filterCache = await prisma.filterCache.upsert({
   *   create: {
   *     // ... data to create a FilterCache
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the FilterCache we want to update
   *   }
   * })
   */
  upsert<T extends FilterCacheUpsertArgs>(args: Prisma.SelectSubset<T, FilterCacheUpsertArgs<ExtArgs>>): Prisma.Prisma__FilterCacheClient<runtime.Types.Result.GetResult<Prisma.$FilterCachePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of FilterCaches.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FilterCacheCountArgs} args - Arguments to filter FilterCaches to count.
   * @example
   * // Count the number of FilterCaches
   * const count = await prisma.filterCache.count({
   *   where: {
   *     // ... the filter for the FilterCaches we want to count
   *   }
   * })
  **/
  count<T extends FilterCacheCountArgs>(
    args?: Prisma.Subset<T, FilterCacheCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], FilterCacheCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a FilterCache.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FilterCacheAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends FilterCacheAggregateArgs>(args: Prisma.Subset<T, FilterCacheAggregateArgs>): Prisma.PrismaPromise<GetFilterCacheAggregateType<T>>

  /**
   * Group by FilterCache.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FilterCacheGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends FilterCacheGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: FilterCacheGroupByArgs['orderBy'] }
      : { orderBy?: FilterCacheGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, FilterCacheGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetFilterCacheGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the FilterCache model
 */
readonly fields: FilterCacheFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for FilterCache.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__FilterCacheClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the FilterCache model
 */
export interface FilterCacheFieldRefs {
  readonly id: Prisma.FieldRef<"FilterCache", 'String'>
  readonly source: Prisma.FieldRef<"FilterCache", 'String'>
  readonly content: Prisma.FieldRef<"FilterCache", 'String'>
  readonly hash: Prisma.FieldRef<"FilterCache", 'String'>
  readonly etag: Prisma.FieldRef<"FilterCache", 'String'>
  readonly createdAt: Prisma.FieldRef<"FilterCache", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"FilterCache", 'DateTime'>
  readonly expiresAt: Prisma.FieldRef<"FilterCache", 'DateTime'>
}
    

// Custom InputTypes
/**
 * FilterCache findUnique
 */
export type FilterCacheFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FilterCache
   */
  select?: Prisma.FilterCacheSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FilterCache
   */
  omit?: Prisma.FilterCacheOmit<ExtArgs> | null
  /**
   * Filter, which FilterCache to fetch.
   */
  where: Prisma.FilterCacheWhereUniqueInput
}

/**
 * FilterCache findUniqueOrThrow
 */
export type FilterCacheFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FilterCache
   */
  select?: Prisma.FilterCacheSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FilterCache
   */
  omit?: Prisma.FilterCacheOmit<ExtArgs> | null
  /**
   * Filter, which FilterCache to fetch.
   */
  where: Prisma.FilterCacheWhereUniqueInput
}

/**
 * FilterCache findFirst
 */
export type FilterCacheFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FilterCache
   */
  select?: Prisma.FilterCacheSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FilterCache
   */
  omit?: Prisma.FilterCacheOmit<ExtArgs> | null
  /**
   * Filter, which FilterCache to fetch.
   */
  where?: Prisma.FilterCacheWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FilterCaches to fetch.
   */
  orderBy?: Prisma.FilterCacheOrderByWithRelationInput | Prisma.FilterCacheOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for FilterCaches.
   */
  cursor?: Prisma.FilterCacheWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FilterCaches from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FilterCaches.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FilterCaches.
   */
  distinct?: Prisma.FilterCacheScalarFieldEnum | Prisma.FilterCacheScalarFieldEnum[]
}

/**
 * FilterCache findFirstOrThrow
 */
export type FilterCacheFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FilterCache
   */
  select?: Prisma.FilterCacheSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FilterCache
   */
  omit?: Prisma.FilterCacheOmit<ExtArgs> | null
  /**
   * Filter, which FilterCache to fetch.
   */
  where?: Prisma.FilterCacheWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FilterCaches to fetch.
   */
  orderBy?: Prisma.FilterCacheOrderByWithRelationInput | Prisma.FilterCacheOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for FilterCaches.
   */
  cursor?: Prisma.FilterCacheWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FilterCaches from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FilterCaches.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FilterCaches.
   */
  distinct?: Prisma.FilterCacheScalarFieldEnum | Prisma.FilterCacheScalarFieldEnum[]
}

/**
 * FilterCache findMany
 */
export type FilterCacheFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FilterCache
   */
  select?: Prisma.FilterCacheSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FilterCache
   */
  omit?: Prisma.FilterCacheOmit<ExtArgs> | null
  /**
   * Filter, which FilterCaches to fetch.
   */
  where?: Prisma.FilterCacheWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FilterCaches to fetch.
   */
  orderBy?: Prisma.FilterCacheOrderByWithRelationInput | Prisma.FilterCacheOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing FilterCaches.
   */
  cursor?: Prisma.FilterCacheWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FilterCaches from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FilterCaches.
   */
  skip?: number
  distinct?: Prisma.FilterCacheScalarFieldEnum | Prisma.FilterCacheScalarFieldEnum[]
}

/**
 * FilterCache create
 */
export type FilterCacheCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FilterCache
   */
  select?: Prisma.FilterCacheSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FilterCache
   */
  omit?: Prisma.FilterCacheOmit<ExtArgs> | null
  /**
   * The data needed to create a FilterCache.
   */
  data: Prisma.XOR<Prisma.FilterCacheCreateInput, Prisma.FilterCacheUncheckedCreateInput>
}

/**
 * FilterCache createMany
 */
export type FilterCacheCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many FilterCaches.
   */
  data: Prisma.FilterCacheCreateManyInput | Prisma.FilterCacheCreateManyInput[]
}

/**
 * FilterCache createManyAndReturn
 */
export type FilterCacheCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FilterCache
   */
  select?: Prisma.FilterCacheSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the FilterCache
   */
  omit?: Prisma.FilterCacheOmit<ExtArgs> | null
  /**
   * The data used to create many FilterCaches.
   */
  data: Prisma.FilterCacheCreateManyInput | Prisma.FilterCacheCreateManyInput[]
}

/**
 * FilterCache update
 */
export type FilterCacheUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FilterCache
   */
  select?: Prisma.FilterCacheSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FilterCache
   */
  omit?: Prisma.FilterCacheOmit<ExtArgs> | null
  /**
   * The data needed to update a FilterCache.
   */
  data: Prisma.XOR<Prisma.FilterCacheUpdateInput, Prisma.FilterCacheUncheckedUpdateInput>
  /**
   * Choose, which FilterCache to update.
   */
  where: Prisma.FilterCacheWhereUniqueInput
}

/**
 * FilterCache updateMany
 */
export type FilterCacheUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update FilterCaches.
   */
  data: Prisma.XOR<Prisma.FilterCacheUpdateManyMutationInput, Prisma.FilterCacheUncheckedUpdateManyInput>
  /**
   * Filter which FilterCaches to update
   */
  where?: Prisma.FilterCacheWhereInput
  /**
   * Limit how many FilterCaches to update.
   */
  limit?: number
}

/**
 * FilterCache updateManyAndReturn
 */
export type FilterCacheUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FilterCache
   */
  select?: Prisma.FilterCacheSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the FilterCache
   */
  omit?: Prisma.FilterCacheOmit<ExtArgs> | null
  /**
   * The data used to update FilterCaches.
   */
  data: Prisma.XOR<Prisma.FilterCacheUpdateManyMutationInput, Prisma.FilterCacheUncheckedUpdateManyInput>
  /**
   * Filter which FilterCaches to update
   */
  where?: Prisma.FilterCacheWhereInput
  /**
   * Limit how many FilterCaches to update.
   */
  limit?: number
}

/**
 * FilterCache upsert
 */
export type FilterCacheUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FilterCache
   */
  select?: Prisma.FilterCacheSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FilterCache
   */
  omit?: Prisma.FilterCacheOmit<ExtArgs> | null
  /**
   * The filter to search for the FilterCache to update in case it exists.
   */
  where: Prisma.FilterCacheWhereUniqueInput
  /**
   * In case the FilterCache found by the `where` argument doesn't exist, create a new FilterCache with this data.
   */
  create: Prisma.XOR<Prisma.FilterCacheCreateInput, Prisma.FilterCacheUncheckedCreateInput>
  /**
   * In case the FilterCache was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.FilterCacheUpdateInput, Prisma.FilterCacheUncheckedUpdateInput>
}

/**
 * FilterCache delete
 */
export type FilterCacheDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FilterCache
   */
  select?: Prisma.FilterCacheSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FilterCache
   */
  omit?: Prisma.FilterCacheOmit<ExtArgs> | null
  /**
   * Filter which FilterCache to delete.
   */
  where: Prisma.FilterCacheWhereUniqueInput
}

/**
 * FilterCache deleteMany
 */
export type FilterCacheDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which FilterCaches to delete
   */
  where?: Prisma.FilterCacheWhereInput
  /**
   * Limit how many FilterCaches to delete.
   */
  limit?: number
}

/**
 * FilterCache without action
 */
export type FilterCacheDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FilterCache
   */
  select?: Prisma.FilterCacheSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FilterCache
   */
  omit?: Prisma.FilterCacheOmit<ExtArgs> | null
}
