
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `SourceHealth` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model SourceHealth
 * 
 */
export type SourceHealthModel = runtime.Types.Result.DefaultSelection<Prisma.$SourceHealthPayload>

export type AggregateSourceHealth = {
  _count: SourceHealthCountAggregateOutputType | null
  _avg: SourceHealthAvgAggregateOutputType | null
  _sum: SourceHealthSumAggregateOutputType | null
  _min: SourceHealthMinAggregateOutputType | null
  _max: SourceHealthMaxAggregateOutputType | null
}

export type SourceHealthAvgAggregateOutputType = {
  totalAttempts: number | null
  successfulAttempts: number | null
  failedAttempts: number | null
  consecutiveFailures: number | null
  averageDuration: number | null
  averageRuleCount: number | null
}

export type SourceHealthSumAggregateOutputType = {
  totalAttempts: number | null
  successfulAttempts: number | null
  failedAttempts: number | null
  consecutiveFailures: number | null
  averageDuration: number | null
  averageRuleCount: number | null
}

export type SourceHealthMinAggregateOutputType = {
  id: string | null
  source: string | null
  status: string | null
  totalAttempts: number | null
  successfulAttempts: number | null
  failedAttempts: number | null
  consecutiveFailures: number | null
  averageDuration: number | null
  averageRuleCount: number | null
  lastAttemptAt: Date | null
  lastSuccessAt: Date | null
  lastFailureAt: Date | null
  recentAttempts: string | null
  updatedAt: Date | null
}

export type SourceHealthMaxAggregateOutputType = {
  id: string | null
  source: string | null
  status: string | null
  totalAttempts: number | null
  successfulAttempts: number | null
  failedAttempts: number | null
  consecutiveFailures: number | null
  averageDuration: number | null
  averageRuleCount: number | null
  lastAttemptAt: Date | null
  lastSuccessAt: Date | null
  lastFailureAt: Date | null
  recentAttempts: string | null
  updatedAt: Date | null
}

export type SourceHealthCountAggregateOutputType = {
  id: number
  source: number
  status: number
  totalAttempts: number
  successfulAttempts: number
  failedAttempts: number
  consecutiveFailures: number
  averageDuration: number
  averageRuleCount: number
  lastAttemptAt: number
  lastSuccessAt: number
  lastFailureAt: number
  recentAttempts: number
  updatedAt: number
  _all: number
}


export type SourceHealthAvgAggregateInputType = {
  totalAttempts?: true
  successfulAttempts?: true
  failedAttempts?: true
  consecutiveFailures?: true
  averageDuration?: true
  averageRuleCount?: true
}

export type SourceHealthSumAggregateInputType = {
  totalAttempts?: true
  successfulAttempts?: true
  failedAttempts?: true
  consecutiveFailures?: true
  averageDuration?: true
  averageRuleCount?: true
}

export type SourceHealthMinAggregateInputType = {
  id?: true
  source?: true
  status?: true
  totalAttempts?: true
  successfulAttempts?: true
  failedAttempts?: true
  consecutiveFailures?: true
  averageDuration?: true
  averageRuleCount?: true
  lastAttemptAt?: true
  lastSuccessAt?: true
  lastFailureAt?: true
  recentAttempts?: true
  updatedAt?: true
}

export type SourceHealthMaxAggregateInputType = {
  id?: true
  source?: true
  status?: true
  totalAttempts?: true
  successfulAttempts?: true
  failedAttempts?: true
  consecutiveFailures?: true
  averageDuration?: true
  averageRuleCount?: true
  lastAttemptAt?: true
  lastSuccessAt?: true
  lastFailureAt?: true
  recentAttempts?: true
  updatedAt?: true
}

export type SourceHealthCountAggregateInputType = {
  id?: true
  source?: true
  status?: true
  totalAttempts?: true
  successfulAttempts?: true
  failedAttempts?: true
  consecutiveFailures?: true
  averageDuration?: true
  averageRuleCount?: true
  lastAttemptAt?: true
  lastSuccessAt?: true
  lastFailureAt?: true
  recentAttempts?: true
  updatedAt?: true
  _all?: true
}

export type SourceHealthAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SourceHealth to aggregate.
   */
  where?: Prisma.SourceHealthWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SourceHealths to fetch.
   */
  orderBy?: Prisma.SourceHealthOrderByWithRelationInput | Prisma.SourceHealthOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SourceHealthWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SourceHealths from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SourceHealths.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned SourceHealths
  **/
  _count?: true | SourceHealthCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: SourceHealthAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: SourceHealthSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SourceHealthMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SourceHealthMaxAggregateInputType
}

export type GetSourceHealthAggregateType<T extends SourceHealthAggregateArgs> = {
      [P in keyof T & keyof AggregateSourceHealth]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSourceHealth[P]>
    : Prisma.GetScalarType<T[P], AggregateSourceHealth[P]>
}




export type SourceHealthGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SourceHealthWhereInput
  orderBy?: Prisma.SourceHealthOrderByWithAggregationInput | Prisma.SourceHealthOrderByWithAggregationInput[]
  by: Prisma.SourceHealthScalarFieldEnum[] | Prisma.SourceHealthScalarFieldEnum
  having?: Prisma.SourceHealthScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SourceHealthCountAggregateInputType | true
  _avg?: SourceHealthAvgAggregateInputType
  _sum?: SourceHealthSumAggregateInputType
  _min?: SourceHealthMinAggregateInputType
  _max?: SourceHealthMaxAggregateInputType
}

export type SourceHealthGroupByOutputType = {
  id: string
  source: string
  status: string
  totalAttempts: number
  successfulAttempts: number
  failedAttempts: number
  consecutiveFailures: number
  averageDuration: number
  averageRuleCount: number
  lastAttemptAt: Date | null
  lastSuccessAt: Date | null
  lastFailureAt: Date | null
  recentAttempts: string | null
  updatedAt: Date
  _count: SourceHealthCountAggregateOutputType | null
  _avg: SourceHealthAvgAggregateOutputType | null
  _sum: SourceHealthSumAggregateOutputType | null
  _min: SourceHealthMinAggregateOutputType | null
  _max: SourceHealthMaxAggregateOutputType | null
}

type GetSourceHealthGroupByPayload<T extends SourceHealthGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SourceHealthGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SourceHealthGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SourceHealthGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SourceHealthGroupByOutputType[P]>
      }
    >
  >



export type SourceHealthWhereInput = {
  AND?: Prisma.SourceHealthWhereInput | Prisma.SourceHealthWhereInput[]
  OR?: Prisma.SourceHealthWhereInput[]
  NOT?: Prisma.SourceHealthWhereInput | Prisma.SourceHealthWhereInput[]
  id?: Prisma.StringFilter<"SourceHealth"> | string
  source?: Prisma.StringFilter<"SourceHealth"> | string
  status?: Prisma.StringFilter<"SourceHealth"> | string
  totalAttempts?: Prisma.IntFilter<"SourceHealth"> | number
  successfulAttempts?: Prisma.IntFilter<"SourceHealth"> | number
  failedAttempts?: Prisma.IntFilter<"SourceHealth"> | number
  consecutiveFailures?: Prisma.IntFilter<"SourceHealth"> | number
  averageDuration?: Prisma.FloatFilter<"SourceHealth"> | number
  averageRuleCount?: Prisma.FloatFilter<"SourceHealth"> | number
  lastAttemptAt?: Prisma.DateTimeNullableFilter<"SourceHealth"> | Date | string | null
  lastSuccessAt?: Prisma.DateTimeNullableFilter<"SourceHealth"> | Date | string | null
  lastFailureAt?: Prisma.DateTimeNullableFilter<"SourceHealth"> | Date | string | null
  recentAttempts?: Prisma.StringNullableFilter<"SourceHealth"> | string | null
  updatedAt?: Prisma.DateTimeFilter<"SourceHealth"> | Date | string
}

export type SourceHealthOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  source?: Prisma.SortOrder
  status?: Prisma.SortOrder
  totalAttempts?: Prisma.SortOrder
  successfulAttempts?: Prisma.SortOrder
  failedAttempts?: Prisma.SortOrder
  consecutiveFailures?: Prisma.SortOrder
  averageDuration?: Prisma.SortOrder
  averageRuleCount?: Prisma.SortOrder
  lastAttemptAt?: Prisma.SortOrderInput | Prisma.SortOrder
  lastSuccessAt?: Prisma.SortOrderInput | Prisma.SortOrder
  lastFailureAt?: Prisma.SortOrderInput | Prisma.SortOrder
  recentAttempts?: Prisma.SortOrderInput | Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type SourceHealthWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  source?: string
  AND?: Prisma.SourceHealthWhereInput | Prisma.SourceHealthWhereInput[]
  OR?: Prisma.SourceHealthWhereInput[]
  NOT?: Prisma.SourceHealthWhereInput | Prisma.SourceHealthWhereInput[]
  status?: Prisma.StringFilter<"SourceHealth"> | string
  totalAttempts?: Prisma.IntFilter<"SourceHealth"> | number
  successfulAttempts?: Prisma.IntFilter<"SourceHealth"> | number
  failedAttempts?: Prisma.IntFilter<"SourceHealth"> | number
  consecutiveFailures?: Prisma.IntFilter<"SourceHealth"> | number
  averageDuration?: Prisma.FloatFilter<"SourceHealth"> | number
  averageRuleCount?: Prisma.FloatFilter<"SourceHealth"> | number
  lastAttemptAt?: Prisma.DateTimeNullableFilter<"SourceHealth"> | Date | string | null
  lastSuccessAt?: Prisma.DateTimeNullableFilter<"SourceHealth"> | Date | string | null
  lastFailureAt?: Prisma.DateTimeNullableFilter<"SourceHealth"> | Date | string | null
  recentAttempts?: Prisma.StringNullableFilter<"SourceHealth"> | string | null
  updatedAt?: Prisma.DateTimeFilter<"SourceHealth"> | Date | string
}, "id" | "source">

export type SourceHealthOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  source?: Prisma.SortOrder
  status?: Prisma.SortOrder
  totalAttempts?: Prisma.SortOrder
  successfulAttempts?: Prisma.SortOrder
  failedAttempts?: Prisma.SortOrder
  consecutiveFailures?: Prisma.SortOrder
  averageDuration?: Prisma.SortOrder
  averageRuleCount?: Prisma.SortOrder
  lastAttemptAt?: Prisma.SortOrderInput | Prisma.SortOrder
  lastSuccessAt?: Prisma.SortOrderInput | Prisma.SortOrder
  lastFailureAt?: Prisma.SortOrderInput | Prisma.SortOrder
  recentAttempts?: Prisma.SortOrderInput | Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.SourceHealthCountOrderByAggregateInput
  _avg?: Prisma.SourceHealthAvgOrderByAggregateInput
  _max?: Prisma.SourceHealthMaxOrderByAggregateInput
  _min?: Prisma.SourceHealthMinOrderByAggregateInput
  _sum?: Prisma.SourceHealthSumOrderByAggregateInput
}

export type SourceHealthScalarWhereWithAggregatesInput = {
  AND?: Prisma.SourceHealthScalarWhereWithAggregatesInput | Prisma.SourceHealthScalarWhereWithAggregatesInput[]
  OR?: Prisma.SourceHealthScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SourceHealthScalarWhereWithAggregatesInput | Prisma.SourceHealthScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"SourceHealth"> | string
  source?: Prisma.StringWithAggregatesFilter<"SourceHealth"> | string
  status?: Prisma.StringWithAggregatesFilter<"SourceHealth"> | string
  totalAttempts?: Prisma.IntWithAggregatesFilter<"SourceHealth"> | number
  successfulAttempts?: Prisma.IntWithAggregatesFilter<"SourceHealth"> | number
  failedAttempts?: Prisma.IntWithAggregatesFilter<"SourceHealth"> | number
  consecutiveFailures?: Prisma.IntWithAggregatesFilter<"SourceHealth"> | number
  averageDuration?: Prisma.FloatWithAggregatesFilter<"SourceHealth"> | number
  averageRuleCount?: Prisma.FloatWithAggregatesFilter<"SourceHealth"> | number
  lastAttemptAt?: Prisma.DateTimeNullableWithAggregatesFilter<"SourceHealth"> | Date | string | null
  lastSuccessAt?: Prisma.DateTimeNullableWithAggregatesFilter<"SourceHealth"> | Date | string | null
  lastFailureAt?: Prisma.DateTimeNullableWithAggregatesFilter<"SourceHealth"> | Date | string | null
  recentAttempts?: Prisma.StringNullableWithAggregatesFilter<"SourceHealth"> | string | null
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"SourceHealth"> | Date | string
}

export type SourceHealthCreateInput = {
  id?: string
  source: string
  status: string
  totalAttempts?: number
  successfulAttempts?: number
  failedAttempts?: number
  consecutiveFailures?: number
  averageDuration?: number
  averageRuleCount?: number
  lastAttemptAt?: Date | string | null
  lastSuccessAt?: Date | string | null
  lastFailureAt?: Date | string | null
  recentAttempts?: string | null
  updatedAt?: Date | string
}

export type SourceHealthUncheckedCreateInput = {
  id?: string
  source: string
  status: string
  totalAttempts?: number
  successfulAttempts?: number
  failedAttempts?: number
  consecutiveFailures?: number
  averageDuration?: number
  averageRuleCount?: number
  lastAttemptAt?: Date | string | null
  lastSuccessAt?: Date | string | null
  lastFailureAt?: Date | string | null
  recentAttempts?: string | null
  updatedAt?: Date | string
}

export type SourceHealthUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  source?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  totalAttempts?: Prisma.IntFieldUpdateOperationsInput | number
  successfulAttempts?: Prisma.IntFieldUpdateOperationsInput | number
  failedAttempts?: Prisma.IntFieldUpdateOperationsInput | number
  consecutiveFailures?: Prisma.IntFieldUpdateOperationsInput | number
  averageDuration?: Prisma.FloatFieldUpdateOperationsInput | number
  averageRuleCount?: Prisma.FloatFieldUpdateOperationsInput | number
  lastAttemptAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  lastSuccessAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  lastFailureAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  recentAttempts?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SourceHealthUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  source?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  totalAttempts?: Prisma.IntFieldUpdateOperationsInput | number
  successfulAttempts?: Prisma.IntFieldUpdateOperationsInput | number
  failedAttempts?: Prisma.IntFieldUpdateOperationsInput | number
  consecutiveFailures?: Prisma.IntFieldUpdateOperationsInput | number
  averageDuration?: Prisma.FloatFieldUpdateOperationsInput | number
  averageRuleCount?: Prisma.FloatFieldUpdateOperationsInput | number
  lastAttemptAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  lastSuccessAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  lastFailureAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  recentAttempts?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SourceHealthCreateManyInput = {
  id?: string
  source: string
  status: string
  totalAttempts?: number
  successfulAttempts?: number
  failedAttempts?: number
  consecutiveFailures?: number
  averageDuration?: number
  averageRuleCount?: number
  lastAttemptAt?: Date | string | null
  lastSuccessAt?: Date | string | null
  lastFailureAt?: Date | string | null
  recentAttempts?: string | null
  updatedAt?: Date | string
}

export type SourceHealthUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  source?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  totalAttempts?: Prisma.IntFieldUpdateOperationsInput | number
  successfulAttempts?: Prisma.IntFieldUpdateOperationsInput | number
  failedAttempts?: Prisma.IntFieldUpdateOperationsInput | number
  consecutiveFailures?: Prisma.IntFieldUpdateOperationsInput | number
  averageDuration?: Prisma.FloatFieldUpdateOperationsInput | number
  averageRuleCount?: Prisma.FloatFieldUpdateOperationsInput | number
  lastAttemptAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  lastSuccessAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  lastFailureAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  recentAttempts?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SourceHealthUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  source?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  totalAttempts?: Prisma.IntFieldUpdateOperationsInput | number
  successfulAttempts?: Prisma.IntFieldUpdateOperationsInput | number
  failedAttempts?: Prisma.IntFieldUpdateOperationsInput | number
  consecutiveFailures?: Prisma.IntFieldUpdateOperationsInput | number
  averageDuration?: Prisma.FloatFieldUpdateOperationsInput | number
  averageRuleCount?: Prisma.FloatFieldUpdateOperationsInput | number
  lastAttemptAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  lastSuccessAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  lastFailureAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  recentAttempts?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SourceHealthCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  source?: Prisma.SortOrder
  status?: Prisma.SortOrder
  totalAttempts?: Prisma.SortOrder
  successfulAttempts?: Prisma.SortOrder
  failedAttempts?: Prisma.SortOrder
  consecutiveFailures?: Prisma.SortOrder
  averageDuration?: Prisma.SortOrder
  averageRuleCount?: Prisma.SortOrder
  lastAttemptAt?: Prisma.SortOrder
  lastSuccessAt?: Prisma.SortOrder
  lastFailureAt?: Prisma.SortOrder
  recentAttempts?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type SourceHealthAvgOrderByAggregateInput = {
  totalAttempts?: Prisma.SortOrder
  successfulAttempts?: Prisma.SortOrder
  failedAttempts?: Prisma.SortOrder
  consecutiveFailures?: Prisma.SortOrder
  averageDuration?: Prisma.SortOrder
  averageRuleCount?: Prisma.SortOrder
}

export type SourceHealthMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  source?: Prisma.SortOrder
  status?: Prisma.SortOrder
  totalAttempts?: Prisma.SortOrder
  successfulAttempts?: Prisma.SortOrder
  failedAttempts?: Prisma.SortOrder
  consecutiveFailures?: Prisma.SortOrder
  averageDuration?: Prisma.SortOrder
  averageRuleCount?: Prisma.SortOrder
  lastAttemptAt?: Prisma.SortOrder
  lastSuccessAt?: Prisma.SortOrder
  lastFailureAt?: Prisma.SortOrder
  recentAttempts?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type SourceHealthMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  source?: Prisma.SortOrder
  status?: Prisma.SortOrder
  totalAttempts?: Prisma.SortOrder
  successfulAttempts?: Prisma.SortOrder
  failedAttempts?: Prisma.SortOrder
  consecutiveFailures?: Prisma.SortOrder
  averageDuration?: Prisma.SortOrder
  averageRuleCount?: Prisma.SortOrder
  lastAttemptAt?: Prisma.SortOrder
  lastSuccessAt?: Prisma.SortOrder
  lastFailureAt?: Prisma.SortOrder
  recentAttempts?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type SourceHealthSumOrderByAggregateInput = {
  totalAttempts?: Prisma.SortOrder
  successfulAttempts?: Prisma.SortOrder
  failedAttempts?: Prisma.SortOrder
  consecutiveFailures?: Prisma.SortOrder
  averageDuration?: Prisma.SortOrder
  averageRuleCount?: Prisma.SortOrder
}

export type FloatFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}



export type SourceHealthSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  source?: boolean
  status?: boolean
  totalAttempts?: boolean
  successfulAttempts?: boolean
  failedAttempts?: boolean
  consecutiveFailures?: boolean
  averageDuration?: boolean
  averageRuleCount?: boolean
  lastAttemptAt?: boolean
  lastSuccessAt?: boolean
  lastFailureAt?: boolean
  recentAttempts?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["sourceHealth"]>

export type SourceHealthSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  source?: boolean
  status?: boolean
  totalAttempts?: boolean
  successfulAttempts?: boolean
  failedAttempts?: boolean
  consecutiveFailures?: boolean
  averageDuration?: boolean
  averageRuleCount?: boolean
  lastAttemptAt?: boolean
  lastSuccessAt?: boolean
  lastFailureAt?: boolean
  recentAttempts?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["sourceHealth"]>

export type SourceHealthSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  source?: boolean
  status?: boolean
  totalAttempts?: boolean
  successfulAttempts?: boolean
  failedAttempts?: boolean
  consecutiveFailures?: boolean
  averageDuration?: boolean
  averageRuleCount?: boolean
  lastAttemptAt?: boolean
  lastSuccessAt?: boolean
  lastFailureAt?: boolean
  recentAttempts?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["sourceHealth"]>

export type SourceHealthSelectScalar = {
  id?: boolean
  source?: boolean
  status?: boolean
  totalAttempts?: boolean
  successfulAttempts?: boolean
  failedAttempts?: boolean
  consecutiveFailures?: boolean
  averageDuration?: boolean
  averageRuleCount?: boolean
  lastAttemptAt?: boolean
  lastSuccessAt?: boolean
  lastFailureAt?: boolean
  recentAttempts?: boolean
  updatedAt?: boolean
}

export type SourceHealthOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "source" | "status" | "totalAttempts" | "successfulAttempts" | "failedAttempts" | "consecutiveFailures" | "averageDuration" | "averageRuleCount" | "lastAttemptAt" | "lastSuccessAt" | "lastFailureAt" | "recentAttempts" | "updatedAt", ExtArgs["result"]["sourceHealth"]>

export type $SourceHealthPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "SourceHealth"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    source: string
    status: string
    totalAttempts: number
    successfulAttempts: number
    failedAttempts: number
    consecutiveFailures: number
    averageDuration: number
    averageRuleCount: number
    lastAttemptAt: Date | null
    lastSuccessAt: Date | null
    lastFailureAt: Date | null
    recentAttempts: string | null
    updatedAt: Date
  }, ExtArgs["result"]["sourceHealth"]>
  composites: {}
}

export type SourceHealthGetPayload<S extends boolean | null | undefined | SourceHealthDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SourceHealthPayload, S>

export type SourceHealthCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SourceHealthFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SourceHealthCountAggregateInputType | true
  }

export interface SourceHealthDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['SourceHealth'], meta: { name: 'SourceHealth' } }
  /**
   * Find zero or one SourceHealth that matches the filter.
   * @param {SourceHealthFindUniqueArgs} args - Arguments to find a SourceHealth
   * @example
   * // Get one SourceHealth
   * const sourceHealth = await prisma.sourceHealth.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SourceHealthFindUniqueArgs>(args: Prisma.SelectSubset<T, SourceHealthFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SourceHealthClient<runtime.Types.Result.GetResult<Prisma.$SourceHealthPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one SourceHealth that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SourceHealthFindUniqueOrThrowArgs} args - Arguments to find a SourceHealth
   * @example
   * // Get one SourceHealth
   * const sourceHealth = await prisma.sourceHealth.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SourceHealthFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SourceHealthFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SourceHealthClient<runtime.Types.Result.GetResult<Prisma.$SourceHealthPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SourceHealth that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SourceHealthFindFirstArgs} args - Arguments to find a SourceHealth
   * @example
   * // Get one SourceHealth
   * const sourceHealth = await prisma.sourceHealth.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SourceHealthFindFirstArgs>(args?: Prisma.SelectSubset<T, SourceHealthFindFirstArgs<ExtArgs>>): Prisma.Prisma__SourceHealthClient<runtime.Types.Result.GetResult<Prisma.$SourceHealthPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SourceHealth that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SourceHealthFindFirstOrThrowArgs} args - Arguments to find a SourceHealth
   * @example
   * // Get one SourceHealth
   * const sourceHealth = await prisma.sourceHealth.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SourceHealthFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SourceHealthFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SourceHealthClient<runtime.Types.Result.GetResult<Prisma.$SourceHealthPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more SourceHealths that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SourceHealthFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all SourceHealths
   * const sourceHealths = await prisma.sourceHealth.findMany()
   * 
   * // Get first 10 SourceHealths
   * const sourceHealths = await prisma.sourceHealth.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const sourceHealthWithIdOnly = await prisma.sourceHealth.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends SourceHealthFindManyArgs>(args?: Prisma.SelectSubset<T, SourceHealthFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SourceHealthPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a SourceHealth.
   * @param {SourceHealthCreateArgs} args - Arguments to create a SourceHealth.
   * @example
   * // Create one SourceHealth
   * const SourceHealth = await prisma.sourceHealth.create({
   *   data: {
   *     // ... data to create a SourceHealth
   *   }
   * })
   * 
   */
  create<T extends SourceHealthCreateArgs>(args: Prisma.SelectSubset<T, SourceHealthCreateArgs<ExtArgs>>): Prisma.Prisma__SourceHealthClient<runtime.Types.Result.GetResult<Prisma.$SourceHealthPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many SourceHealths.
   * @param {SourceHealthCreateManyArgs} args - Arguments to create many SourceHealths.
   * @example
   * // Create many SourceHealths
   * const sourceHealth = await prisma.sourceHealth.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SourceHealthCreateManyArgs>(args?: Prisma.SelectSubset<T, SourceHealthCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many SourceHealths and returns the data saved in the database.
   * @param {SourceHealthCreateManyAndReturnArgs} args - Arguments to create many SourceHealths.
   * @example
   * // Create many SourceHealths
   * const sourceHealth = await prisma.sourceHealth.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many SourceHealths and only return the `id`
   * const sourceHealthWithIdOnly = await prisma.sourceHealth.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends SourceHealthCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, SourceHealthCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SourceHealthPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a SourceHealth.
   * @param {SourceHealthDeleteArgs} args - Arguments to delete one SourceHealth.
   * @example
   * // Delete one SourceHealth
   * const SourceHealth = await prisma.sourceHealth.delete({
   *   where: {
   *     // ... filter to delete one SourceHealth
   *   }
   * })
   * 
   */
  delete<T extends SourceHealthDeleteArgs>(args: Prisma.SelectSubset<T, SourceHealthDeleteArgs<ExtArgs>>): Prisma.Prisma__SourceHealthClient<runtime.Types.Result.GetResult<Prisma.$SourceHealthPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one SourceHealth.
   * @param {SourceHealthUpdateArgs} args - Arguments to update one SourceHealth.
   * @example
   * // Update one SourceHealth
   * const sourceHealth = await prisma.sourceHealth.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SourceHealthUpdateArgs>(args: Prisma.SelectSubset<T, SourceHealthUpdateArgs<ExtArgs>>): Prisma.Prisma__SourceHealthClient<runtime.Types.Result.GetResult<Prisma.$SourceHealthPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more SourceHealths.
   * @param {SourceHealthDeleteManyArgs} args - Arguments to filter SourceHealths to delete.
   * @example
   * // Delete a few SourceHealths
   * const { count } = await prisma.sourceHealth.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SourceHealthDeleteManyArgs>(args?: Prisma.SelectSubset<T, SourceHealthDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SourceHealths.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SourceHealthUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many SourceHealths
   * const sourceHealth = await prisma.sourceHealth.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SourceHealthUpdateManyArgs>(args: Prisma.SelectSubset<T, SourceHealthUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SourceHealths and returns the data updated in the database.
   * @param {SourceHealthUpdateManyAndReturnArgs} args - Arguments to update many SourceHealths.
   * @example
   * // Update many SourceHealths
   * const sourceHealth = await prisma.sourceHealth.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more SourceHealths and only return the `id`
   * const sourceHealthWithIdOnly = await prisma.sourceHealth.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends SourceHealthUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, SourceHealthUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SourceHealthPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one SourceHealth.
   * @param {SourceHealthUpsertArgs} args - Arguments to update or create a SourceHealth.
   * @example
   * // Update or create a SourceHealth
   * const sourceHealth = await prisma.sourceHealth.upsert({
   *   create: {
   *     // ... data to create a SourceHealth
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the SourceHealth we want to update
   *   }
   * })
   */
  upsert<T extends SourceHealthUpsertArgs>(args: Prisma.SelectSubset<T, SourceHealthUpsertArgs<ExtArgs>>): Prisma.Prisma__SourceHealthClient<runtime.Types.Result.GetResult<Prisma.$SourceHealthPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of SourceHealths.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SourceHealthCountArgs} args - Arguments to filter SourceHealths to count.
   * @example
   * // Count the number of SourceHealths
   * const count = await prisma.sourceHealth.count({
   *   where: {
   *     // ... the filter for the SourceHealths we want to count
   *   }
   * })
  **/
  count<T extends SourceHealthCountArgs>(
    args?: Prisma.Subset<T, SourceHealthCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SourceHealthCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a SourceHealth.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SourceHealthAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SourceHealthAggregateArgs>(args: Prisma.Subset<T, SourceHealthAggregateArgs>): Prisma.PrismaPromise<GetSourceHealthAggregateType<T>>

  /**
   * Group by SourceHealth.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SourceHealthGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SourceHealthGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SourceHealthGroupByArgs['orderBy'] }
      : { orderBy?: SourceHealthGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SourceHealthGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSourceHealthGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the SourceHealth model
 */
readonly fields: SourceHealthFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for SourceHealth.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SourceHealthClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the SourceHealth model
 */
export interface SourceHealthFieldRefs {
  readonly id: Prisma.FieldRef<"SourceHealth", 'String'>
  readonly source: Prisma.FieldRef<"SourceHealth", 'String'>
  readonly status: Prisma.FieldRef<"SourceHealth", 'String'>
  readonly totalAttempts: Prisma.FieldRef<"SourceHealth", 'Int'>
  readonly successfulAttempts: Prisma.FieldRef<"SourceHealth", 'Int'>
  readonly failedAttempts: Prisma.FieldRef<"SourceHealth", 'Int'>
  readonly consecutiveFailures: Prisma.FieldRef<"SourceHealth", 'Int'>
  readonly averageDuration: Prisma.FieldRef<"SourceHealth", 'Float'>
  readonly averageRuleCount: Prisma.FieldRef<"SourceHealth", 'Float'>
  readonly lastAttemptAt: Prisma.FieldRef<"SourceHealth", 'DateTime'>
  readonly lastSuccessAt: Prisma.FieldRef<"SourceHealth", 'DateTime'>
  readonly lastFailureAt: Prisma.FieldRef<"SourceHealth", 'DateTime'>
  readonly recentAttempts: Prisma.FieldRef<"SourceHealth", 'String'>
  readonly updatedAt: Prisma.FieldRef<"SourceHealth", 'DateTime'>
}
    

// Custom InputTypes
/**
 * SourceHealth findUnique
 */
export type SourceHealthFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SourceHealth
   */
  select?: Prisma.SourceHealthSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SourceHealth
   */
  omit?: Prisma.SourceHealthOmit<ExtArgs> | null
  /**
   * Filter, which SourceHealth to fetch.
   */
  where: Prisma.SourceHealthWhereUniqueInput
}

/**
 * SourceHealth findUniqueOrThrow
 */
export type SourceHealthFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SourceHealth
   */
  select?: Prisma.SourceHealthSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SourceHealth
   */
  omit?: Prisma.SourceHealthOmit<ExtArgs> | null
  /**
   * Filter, which SourceHealth to fetch.
   */
  where: Prisma.SourceHealthWhereUniqueInput
}

/**
 * SourceHealth findFirst
 */
export type SourceHealthFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SourceHealth
   */
  select?: Prisma.SourceHealthSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SourceHealth
   */
  omit?: Prisma.SourceHealthOmit<ExtArgs> | null
  /**
   * Filter, which SourceHealth to fetch.
   */
  where?: Prisma.SourceHealthWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SourceHealths to fetch.
   */
  orderBy?: Prisma.SourceHealthOrderByWithRelationInput | Prisma.SourceHealthOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SourceHealths.
   */
  cursor?: Prisma.SourceHealthWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SourceHealths from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SourceHealths.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SourceHealths.
   */
  distinct?: Prisma.SourceHealthScalarFieldEnum | Prisma.SourceHealthScalarFieldEnum[]
}

/**
 * SourceHealth findFirstOrThrow
 */
export type SourceHealthFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SourceHealth
   */
  select?: Prisma.SourceHealthSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SourceHealth
   */
  omit?: Prisma.SourceHealthOmit<ExtArgs> | null
  /**
   * Filter, which SourceHealth to fetch.
   */
  where?: Prisma.SourceHealthWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SourceHealths to fetch.
   */
  orderBy?: Prisma.SourceHealthOrderByWithRelationInput | Prisma.SourceHealthOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SourceHealths.
   */
  cursor?: Prisma.SourceHealthWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SourceHealths from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SourceHealths.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SourceHealths.
   */
  distinct?: Prisma.SourceHealthScalarFieldEnum | Prisma.SourceHealthScalarFieldEnum[]
}

/**
 * SourceHealth findMany
 */
export type SourceHealthFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SourceHealth
   */
  select?: Prisma.SourceHealthSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SourceHealth
   */
  omit?: Prisma.SourceHealthOmit<ExtArgs> | null
  /**
   * Filter, which SourceHealths to fetch.
   */
  where?: Prisma.SourceHealthWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SourceHealths to fetch.
   */
  orderBy?: Prisma.SourceHealthOrderByWithRelationInput | Prisma.SourceHealthOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing SourceHealths.
   */
  cursor?: Prisma.SourceHealthWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SourceHealths from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SourceHealths.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SourceHealths.
   */
  distinct?: Prisma.SourceHealthScalarFieldEnum | Prisma.SourceHealthScalarFieldEnum[]
}

/**
 * SourceHealth create
 */
export type SourceHealthCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SourceHealth
   */
  select?: Prisma.SourceHealthSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SourceHealth
   */
  omit?: Prisma.SourceHealthOmit<ExtArgs> | null
  /**
   * The data needed to create a SourceHealth.
   */
  data: Prisma.XOR<Prisma.SourceHealthCreateInput, Prisma.SourceHealthUncheckedCreateInput>
}

/**
 * SourceHealth createMany
 */
export type SourceHealthCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many SourceHealths.
   */
  data: Prisma.SourceHealthCreateManyInput | Prisma.SourceHealthCreateManyInput[]
}

/**
 * SourceHealth createManyAndReturn
 */
export type SourceHealthCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SourceHealth
   */
  select?: Prisma.SourceHealthSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SourceHealth
   */
  omit?: Prisma.SourceHealthOmit<ExtArgs> | null
  /**
   * The data used to create many SourceHealths.
   */
  data: Prisma.SourceHealthCreateManyInput | Prisma.SourceHealthCreateManyInput[]
}

/**
 * SourceHealth update
 */
export type SourceHealthUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SourceHealth
   */
  select?: Prisma.SourceHealthSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SourceHealth
   */
  omit?: Prisma.SourceHealthOmit<ExtArgs> | null
  /**
   * The data needed to update a SourceHealth.
   */
  data: Prisma.XOR<Prisma.SourceHealthUpdateInput, Prisma.SourceHealthUncheckedUpdateInput>
  /**
   * Choose, which SourceHealth to update.
   */
  where: Prisma.SourceHealthWhereUniqueInput
}

/**
 * SourceHealth updateMany
 */
export type SourceHealthUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update SourceHealths.
   */
  data: Prisma.XOR<Prisma.SourceHealthUpdateManyMutationInput, Prisma.SourceHealthUncheckedUpdateManyInput>
  /**
   * Filter which SourceHealths to update
   */
  where?: Prisma.SourceHealthWhereInput
  /**
   * Limit how many SourceHealths to update.
   */
  limit?: number
}

/**
 * SourceHealth updateManyAndReturn
 */
export type SourceHealthUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SourceHealth
   */
  select?: Prisma.SourceHealthSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SourceHealth
   */
  omit?: Prisma.SourceHealthOmit<ExtArgs> | null
  /**
   * The data used to update SourceHealths.
   */
  data: Prisma.XOR<Prisma.SourceHealthUpdateManyMutationInput, Prisma.SourceHealthUncheckedUpdateManyInput>
  /**
   * Filter which SourceHealths to update
   */
  where?: Prisma.SourceHealthWhereInput
  /**
   * Limit how many SourceHealths to update.
   */
  limit?: number
}

/**
 * SourceHealth upsert
 */
export type SourceHealthUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SourceHealth
   */
  select?: Prisma.SourceHealthSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SourceHealth
   */
  omit?: Prisma.SourceHealthOmit<ExtArgs> | null
  /**
   * The filter to search for the SourceHealth to update in case it exists.
   */
  where: Prisma.SourceHealthWhereUniqueInput
  /**
   * In case the SourceHealth found by the `where` argument doesn't exist, create a new SourceHealth with this data.
   */
  create: Prisma.XOR<Prisma.SourceHealthCreateInput, Prisma.SourceHealthUncheckedCreateInput>
  /**
   * In case the SourceHealth was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SourceHealthUpdateInput, Prisma.SourceHealthUncheckedUpdateInput>
}

/**
 * SourceHealth delete
 */
export type SourceHealthDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SourceHealth
   */
  select?: Prisma.SourceHealthSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SourceHealth
   */
  omit?: Prisma.SourceHealthOmit<ExtArgs> | null
  /**
   * Filter which SourceHealth to delete.
   */
  where: Prisma.SourceHealthWhereUniqueInput
}

/**
 * SourceHealth deleteMany
 */
export type SourceHealthDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SourceHealths to delete
   */
  where?: Prisma.SourceHealthWhereInput
  /**
   * Limit how many SourceHealths to delete.
   */
  limit?: number
}

/**
 * SourceHealth without action
 */
export type SourceHealthDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SourceHealth
   */
  select?: Prisma.SourceHealthSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SourceHealth
   */
  omit?: Prisma.SourceHealthOmit<ExtArgs> | null
}
