
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `SourceAttempt` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model SourceAttempt
 * 
 */
export type SourceAttemptModel = runtime.Types.Result.DefaultSelection<Prisma.$SourceAttemptPayload>

export type AggregateSourceAttempt = {
  _count: SourceAttemptCountAggregateOutputType | null
  _avg: SourceAttemptAvgAggregateOutputType | null
  _sum: SourceAttemptSumAggregateOutputType | null
  _min: SourceAttemptMinAggregateOutputType | null
  _max: SourceAttemptMaxAggregateOutputType | null
}

export type SourceAttemptAvgAggregateOutputType = {
  success: number | null
  duration: number | null
  ruleCount: number | null
}

export type SourceAttemptSumAggregateOutputType = {
  success: number | null
  duration: number | null
  ruleCount: number | null
}

export type SourceAttemptMinAggregateOutputType = {
  id: string | null
  source: string | null
  timestamp: Date | null
  success: number | null
  duration: number | null
  error: string | null
  ruleCount: number | null
  etag: string | null
}

export type SourceAttemptMaxAggregateOutputType = {
  id: string | null
  source: string | null
  timestamp: Date | null
  success: number | null
  duration: number | null
  error: string | null
  ruleCount: number | null
  etag: string | null
}

export type SourceAttemptCountAggregateOutputType = {
  id: number
  source: number
  timestamp: number
  success: number
  duration: number
  error: number
  ruleCount: number
  etag: number
  _all: number
}


export type SourceAttemptAvgAggregateInputType = {
  success?: true
  duration?: true
  ruleCount?: true
}

export type SourceAttemptSumAggregateInputType = {
  success?: true
  duration?: true
  ruleCount?: true
}

export type SourceAttemptMinAggregateInputType = {
  id?: true
  source?: true
  timestamp?: true
  success?: true
  duration?: true
  error?: true
  ruleCount?: true
  etag?: true
}

export type SourceAttemptMaxAggregateInputType = {
  id?: true
  source?: true
  timestamp?: true
  success?: true
  duration?: true
  error?: true
  ruleCount?: true
  etag?: true
}

export type SourceAttemptCountAggregateInputType = {
  id?: true
  source?: true
  timestamp?: true
  success?: true
  duration?: true
  error?: true
  ruleCount?: true
  etag?: true
  _all?: true
}

export type SourceAttemptAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SourceAttempt to aggregate.
   */
  where?: Prisma.SourceAttemptWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SourceAttempts to fetch.
   */
  orderBy?: Prisma.SourceAttemptOrderByWithRelationInput | Prisma.SourceAttemptOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SourceAttemptWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SourceAttempts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SourceAttempts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned SourceAttempts
  **/
  _count?: true | SourceAttemptCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: SourceAttemptAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: SourceAttemptSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SourceAttemptMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SourceAttemptMaxAggregateInputType
}

export type GetSourceAttemptAggregateType<T extends SourceAttemptAggregateArgs> = {
      [P in keyof T & keyof AggregateSourceAttempt]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSourceAttempt[P]>
    : Prisma.GetScalarType<T[P], AggregateSourceAttempt[P]>
}




export type SourceAttemptGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SourceAttemptWhereInput
  orderBy?: Prisma.SourceAttemptOrderByWithAggregationInput | Prisma.SourceAttemptOrderByWithAggregationInput[]
  by: Prisma.SourceAttemptScalarFieldEnum[] | Prisma.SourceAttemptScalarFieldEnum
  having?: Prisma.SourceAttemptScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SourceAttemptCountAggregateInputType | true
  _avg?: SourceAttemptAvgAggregateInputType
  _sum?: SourceAttemptSumAggregateInputType
  _min?: SourceAttemptMinAggregateInputType
  _max?: SourceAttemptMaxAggregateInputType
}

export type SourceAttemptGroupByOutputType = {
  id: string
  source: string
  timestamp: Date
  success: number
  duration: number
  error: string | null
  ruleCount: number | null
  etag: string | null
  _count: SourceAttemptCountAggregateOutputType | null
  _avg: SourceAttemptAvgAggregateOutputType | null
  _sum: SourceAttemptSumAggregateOutputType | null
  _min: SourceAttemptMinAggregateOutputType | null
  _max: SourceAttemptMaxAggregateOutputType | null
}

type GetSourceAttemptGroupByPayload<T extends SourceAttemptGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SourceAttemptGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SourceAttemptGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SourceAttemptGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SourceAttemptGroupByOutputType[P]>
      }
    >
  >



export type SourceAttemptWhereInput = {
  AND?: Prisma.SourceAttemptWhereInput | Prisma.SourceAttemptWhereInput[]
  OR?: Prisma.SourceAttemptWhereInput[]
  NOT?: Prisma.SourceAttemptWhereInput | Prisma.SourceAttemptWhereInput[]
  id?: Prisma.StringFilter<"SourceAttempt"> | string
  source?: Prisma.StringFilter<"SourceAttempt"> | string
  timestamp?: Prisma.DateTimeFilter<"SourceAttempt"> | Date | string
  success?: Prisma.IntFilter<"SourceAttempt"> | number
  duration?: Prisma.IntFilter<"SourceAttempt"> | number
  error?: Prisma.StringNullableFilter<"SourceAttempt"> | string | null
  ruleCount?: Prisma.IntNullableFilter<"SourceAttempt"> | number | null
  etag?: Prisma.StringNullableFilter<"SourceAttempt"> | string | null
}

export type SourceAttemptOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  source?: Prisma.SortOrder
  timestamp?: Prisma.SortOrder
  success?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  error?: Prisma.SortOrderInput | Prisma.SortOrder
  ruleCount?: Prisma.SortOrderInput | Prisma.SortOrder
  etag?: Prisma.SortOrderInput | Prisma.SortOrder
}

export type SourceAttemptWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.SourceAttemptWhereInput | Prisma.SourceAttemptWhereInput[]
  OR?: Prisma.SourceAttemptWhereInput[]
  NOT?: Prisma.SourceAttemptWhereInput | Prisma.SourceAttemptWhereInput[]
  source?: Prisma.StringFilter<"SourceAttempt"> | string
  timestamp?: Prisma.DateTimeFilter<"SourceAttempt"> | Date | string
  success?: Prisma.IntFilter<"SourceAttempt"> | number
  duration?: Prisma.IntFilter<"SourceAttempt"> | number
  error?: Prisma.StringNullableFilter<"SourceAttempt"> | string | null
  ruleCount?: Prisma.IntNullableFilter<"SourceAttempt"> | number | null
  etag?: Prisma.StringNullableFilter<"SourceAttempt"> | string | null
}, "id">

export type SourceAttemptOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  source?: Prisma.SortOrder
  timestamp?: Prisma.SortOrder
  success?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  error?: Prisma.SortOrderInput | Prisma.SortOrder
  ruleCount?: Prisma.SortOrderInput | Prisma.SortOrder
  etag?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.SourceAttemptCountOrderByAggregateInput
  _avg?: Prisma.SourceAttemptAvgOrderByAggregateInput
  _max?: Prisma.SourceAttemptMaxOrderByAggregateInput
  _min?: Prisma.SourceAttemptMinOrderByAggregateInput
  _sum?: Prisma.SourceAttemptSumOrderByAggregateInput
}

export type SourceAttemptScalarWhereWithAggregatesInput = {
  AND?: Prisma.SourceAttemptScalarWhereWithAggregatesInput | Prisma.SourceAttemptScalarWhereWithAggregatesInput[]
  OR?: Prisma.SourceAttemptScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SourceAttemptScalarWhereWithAggregatesInput | Prisma.SourceAttemptScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"SourceAttempt"> | string
  source?: Prisma.StringWithAggregatesFilter<"SourceAttempt"> | string
  timestamp?: Prisma.DateTimeWithAggregatesFilter<"SourceAttempt"> | Date | string
  success?: Prisma.IntWithAggregatesFilter<"SourceAttempt"> | number
  duration?: Prisma.IntWithAggregatesFilter<"SourceAttempt"> | number
  error?: Prisma.StringNullableWithAggregatesFilter<"SourceAttempt"> | string | null
  ruleCount?: Prisma.IntNullableWithAggregatesFilter<"SourceAttempt"> | number | null
  etag?: Prisma.StringNullableWithAggregatesFilter<"SourceAttempt"> | string | null
}

export type SourceAttemptCreateInput = {
  id?: string
  source: string
  timestamp?: Date | string
  success?: number
  duration: number
  error?: string | null
  ruleCount?: number | null
  etag?: string | null
}

export type SourceAttemptUncheckedCreateInput = {
  id?: string
  source: string
  timestamp?: Date | string
  success?: number
  duration: number
  error?: string | null
  ruleCount?: number | null
  etag?: string | null
}

export type SourceAttemptUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  source?: Prisma.StringFieldUpdateOperationsInput | string
  timestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  success?: Prisma.IntFieldUpdateOperationsInput | number
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  error?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ruleCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  etag?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type SourceAttemptUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  source?: Prisma.StringFieldUpdateOperationsInput | string
  timestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  success?: Prisma.IntFieldUpdateOperationsInput | number
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  error?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ruleCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  etag?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type SourceAttemptCreateManyInput = {
  id?: string
  source: string
  timestamp?: Date | string
  success?: number
  duration: number
  error?: string | null
  ruleCount?: number | null
  etag?: string | null
}

export type SourceAttemptUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  source?: Prisma.StringFieldUpdateOperationsInput | string
  timestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  success?: Prisma.IntFieldUpdateOperationsInput | number
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  error?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ruleCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  etag?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type SourceAttemptUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  source?: Prisma.StringFieldUpdateOperationsInput | string
  timestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  success?: Prisma.IntFieldUpdateOperationsInput | number
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  error?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ruleCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  etag?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type SourceAttemptCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  source?: Prisma.SortOrder
  timestamp?: Prisma.SortOrder
  success?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  error?: Prisma.SortOrder
  ruleCount?: Prisma.SortOrder
  etag?: Prisma.SortOrder
}

export type SourceAttemptAvgOrderByAggregateInput = {
  success?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  ruleCount?: Prisma.SortOrder
}

export type SourceAttemptMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  source?: Prisma.SortOrder
  timestamp?: Prisma.SortOrder
  success?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  error?: Prisma.SortOrder
  ruleCount?: Prisma.SortOrder
  etag?: Prisma.SortOrder
}

export type SourceAttemptMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  source?: Prisma.SortOrder
  timestamp?: Prisma.SortOrder
  success?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  error?: Prisma.SortOrder
  ruleCount?: Prisma.SortOrder
  etag?: Prisma.SortOrder
}

export type SourceAttemptSumOrderByAggregateInput = {
  success?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  ruleCount?: Prisma.SortOrder
}

export type NullableIntFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}



export type SourceAttemptSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  source?: boolean
  timestamp?: boolean
  success?: boolean
  duration?: boolean
  error?: boolean
  ruleCount?: boolean
  etag?: boolean
}, ExtArgs["result"]["sourceAttempt"]>

export type SourceAttemptSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  source?: boolean
  timestamp?: boolean
  success?: boolean
  duration?: boolean
  error?: boolean
  ruleCount?: boolean
  etag?: boolean
}, ExtArgs["result"]["sourceAttempt"]>

export type SourceAttemptSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  source?: boolean
  timestamp?: boolean
  success?: boolean
  duration?: boolean
  error?: boolean
  ruleCount?: boolean
  etag?: boolean
}, ExtArgs["result"]["sourceAttempt"]>

export type SourceAttemptSelectScalar = {
  id?: boolean
  source?: boolean
  timestamp?: boolean
  success?: boolean
  duration?: boolean
  error?: boolean
  ruleCount?: boolean
  etag?: boolean
}

export type SourceAttemptOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "source" | "timestamp" | "success" | "duration" | "error" | "ruleCount" | "etag", ExtArgs["result"]["sourceAttempt"]>

export type $SourceAttemptPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "SourceAttempt"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    source: string
    timestamp: Date
    success: number
    duration: number
    error: string | null
    ruleCount: number | null
    etag: string | null
  }, ExtArgs["result"]["sourceAttempt"]>
  composites: {}
}

export type SourceAttemptGetPayload<S extends boolean | null | undefined | SourceAttemptDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SourceAttemptPayload, S>

export type SourceAttemptCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SourceAttemptFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SourceAttemptCountAggregateInputType | true
  }

export interface SourceAttemptDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['SourceAttempt'], meta: { name: 'SourceAttempt' } }
  /**
   * Find zero or one SourceAttempt that matches the filter.
   * @param {SourceAttemptFindUniqueArgs} args - Arguments to find a SourceAttempt
   * @example
   * // Get one SourceAttempt
   * const sourceAttempt = await prisma.sourceAttempt.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SourceAttemptFindUniqueArgs>(args: Prisma.SelectSubset<T, SourceAttemptFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SourceAttemptClient<runtime.Types.Result.GetResult<Prisma.$SourceAttemptPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one SourceAttempt that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SourceAttemptFindUniqueOrThrowArgs} args - Arguments to find a SourceAttempt
   * @example
   * // Get one SourceAttempt
   * const sourceAttempt = await prisma.sourceAttempt.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SourceAttemptFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SourceAttemptFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SourceAttemptClient<runtime.Types.Result.GetResult<Prisma.$SourceAttemptPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SourceAttempt that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SourceAttemptFindFirstArgs} args - Arguments to find a SourceAttempt
   * @example
   * // Get one SourceAttempt
   * const sourceAttempt = await prisma.sourceAttempt.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SourceAttemptFindFirstArgs>(args?: Prisma.SelectSubset<T, SourceAttemptFindFirstArgs<ExtArgs>>): Prisma.Prisma__SourceAttemptClient<runtime.Types.Result.GetResult<Prisma.$SourceAttemptPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SourceAttempt that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SourceAttemptFindFirstOrThrowArgs} args - Arguments to find a SourceAttempt
   * @example
   * // Get one SourceAttempt
   * const sourceAttempt = await prisma.sourceAttempt.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SourceAttemptFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SourceAttemptFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SourceAttemptClient<runtime.Types.Result.GetResult<Prisma.$SourceAttemptPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more SourceAttempts that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SourceAttemptFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all SourceAttempts
   * const sourceAttempts = await prisma.sourceAttempt.findMany()
   * 
   * // Get first 10 SourceAttempts
   * const sourceAttempts = await prisma.sourceAttempt.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const sourceAttemptWithIdOnly = await prisma.sourceAttempt.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends SourceAttemptFindManyArgs>(args?: Prisma.SelectSubset<T, SourceAttemptFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SourceAttemptPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a SourceAttempt.
   * @param {SourceAttemptCreateArgs} args - Arguments to create a SourceAttempt.
   * @example
   * // Create one SourceAttempt
   * const SourceAttempt = await prisma.sourceAttempt.create({
   *   data: {
   *     // ... data to create a SourceAttempt
   *   }
   * })
   * 
   */
  create<T extends SourceAttemptCreateArgs>(args: Prisma.SelectSubset<T, SourceAttemptCreateArgs<ExtArgs>>): Prisma.Prisma__SourceAttemptClient<runtime.Types.Result.GetResult<Prisma.$SourceAttemptPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many SourceAttempts.
   * @param {SourceAttemptCreateManyArgs} args - Arguments to create many SourceAttempts.
   * @example
   * // Create many SourceAttempts
   * const sourceAttempt = await prisma.sourceAttempt.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SourceAttemptCreateManyArgs>(args?: Prisma.SelectSubset<T, SourceAttemptCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many SourceAttempts and returns the data saved in the database.
   * @param {SourceAttemptCreateManyAndReturnArgs} args - Arguments to create many SourceAttempts.
   * @example
   * // Create many SourceAttempts
   * const sourceAttempt = await prisma.sourceAttempt.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many SourceAttempts and only return the `id`
   * const sourceAttemptWithIdOnly = await prisma.sourceAttempt.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends SourceAttemptCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, SourceAttemptCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SourceAttemptPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a SourceAttempt.
   * @param {SourceAttemptDeleteArgs} args - Arguments to delete one SourceAttempt.
   * @example
   * // Delete one SourceAttempt
   * const SourceAttempt = await prisma.sourceAttempt.delete({
   *   where: {
   *     // ... filter to delete one SourceAttempt
   *   }
   * })
   * 
   */
  delete<T extends SourceAttemptDeleteArgs>(args: Prisma.SelectSubset<T, SourceAttemptDeleteArgs<ExtArgs>>): Prisma.Prisma__SourceAttemptClient<runtime.Types.Result.GetResult<Prisma.$SourceAttemptPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one SourceAttempt.
   * @param {SourceAttemptUpdateArgs} args - Arguments to update one SourceAttempt.
   * @example
   * // Update one SourceAttempt
   * const sourceAttempt = await prisma.sourceAttempt.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SourceAttemptUpdateArgs>(args: Prisma.SelectSubset<T, SourceAttemptUpdateArgs<ExtArgs>>): Prisma.Prisma__SourceAttemptClient<runtime.Types.Result.GetResult<Prisma.$SourceAttemptPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more SourceAttempts.
   * @param {SourceAttemptDeleteManyArgs} args - Arguments to filter SourceAttempts to delete.
   * @example
   * // Delete a few SourceAttempts
   * const { count } = await prisma.sourceAttempt.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SourceAttemptDeleteManyArgs>(args?: Prisma.SelectSubset<T, SourceAttemptDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SourceAttempts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SourceAttemptUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many SourceAttempts
   * const sourceAttempt = await prisma.sourceAttempt.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SourceAttemptUpdateManyArgs>(args: Prisma.SelectSubset<T, SourceAttemptUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SourceAttempts and returns the data updated in the database.
   * @param {SourceAttemptUpdateManyAndReturnArgs} args - Arguments to update many SourceAttempts.
   * @example
   * // Update many SourceAttempts
   * const sourceAttempt = await prisma.sourceAttempt.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more SourceAttempts and only return the `id`
   * const sourceAttemptWithIdOnly = await prisma.sourceAttempt.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends SourceAttemptUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, SourceAttemptUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SourceAttemptPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one SourceAttempt.
   * @param {SourceAttemptUpsertArgs} args - Arguments to update or create a SourceAttempt.
   * @example
   * // Update or create a SourceAttempt
   * const sourceAttempt = await prisma.sourceAttempt.upsert({
   *   create: {
   *     // ... data to create a SourceAttempt
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the SourceAttempt we want to update
   *   }
   * })
   */
  upsert<T extends SourceAttemptUpsertArgs>(args: Prisma.SelectSubset<T, SourceAttemptUpsertArgs<ExtArgs>>): Prisma.Prisma__SourceAttemptClient<runtime.Types.Result.GetResult<Prisma.$SourceAttemptPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of SourceAttempts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SourceAttemptCountArgs} args - Arguments to filter SourceAttempts to count.
   * @example
   * // Count the number of SourceAttempts
   * const count = await prisma.sourceAttempt.count({
   *   where: {
   *     // ... the filter for the SourceAttempts we want to count
   *   }
   * })
  **/
  count<T extends SourceAttemptCountArgs>(
    args?: Prisma.Subset<T, SourceAttemptCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SourceAttemptCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a SourceAttempt.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SourceAttemptAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SourceAttemptAggregateArgs>(args: Prisma.Subset<T, SourceAttemptAggregateArgs>): Prisma.PrismaPromise<GetSourceAttemptAggregateType<T>>

  /**
   * Group by SourceAttempt.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SourceAttemptGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SourceAttemptGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SourceAttemptGroupByArgs['orderBy'] }
      : { orderBy?: SourceAttemptGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SourceAttemptGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSourceAttemptGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the SourceAttempt model
 */
readonly fields: SourceAttemptFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for SourceAttempt.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SourceAttemptClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the SourceAttempt model
 */
export interface SourceAttemptFieldRefs {
  readonly id: Prisma.FieldRef<"SourceAttempt", 'String'>
  readonly source: Prisma.FieldRef<"SourceAttempt", 'String'>
  readonly timestamp: Prisma.FieldRef<"SourceAttempt", 'DateTime'>
  readonly success: Prisma.FieldRef<"SourceAttempt", 'Int'>
  readonly duration: Prisma.FieldRef<"SourceAttempt", 'Int'>
  readonly error: Prisma.FieldRef<"SourceAttempt", 'String'>
  readonly ruleCount: Prisma.FieldRef<"SourceAttempt", 'Int'>
  readonly etag: Prisma.FieldRef<"SourceAttempt", 'String'>
}
    

// Custom InputTypes
/**
 * SourceAttempt findUnique
 */
export type SourceAttemptFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SourceAttempt
   */
  select?: Prisma.SourceAttemptSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SourceAttempt
   */
  omit?: Prisma.SourceAttemptOmit<ExtArgs> | null
  /**
   * Filter, which SourceAttempt to fetch.
   */
  where: Prisma.SourceAttemptWhereUniqueInput
}

/**
 * SourceAttempt findUniqueOrThrow
 */
export type SourceAttemptFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SourceAttempt
   */
  select?: Prisma.SourceAttemptSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SourceAttempt
   */
  omit?: Prisma.SourceAttemptOmit<ExtArgs> | null
  /**
   * Filter, which SourceAttempt to fetch.
   */
  where: Prisma.SourceAttemptWhereUniqueInput
}

/**
 * SourceAttempt findFirst
 */
export type SourceAttemptFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SourceAttempt
   */
  select?: Prisma.SourceAttemptSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SourceAttempt
   */
  omit?: Prisma.SourceAttemptOmit<ExtArgs> | null
  /**
   * Filter, which SourceAttempt to fetch.
   */
  where?: Prisma.SourceAttemptWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SourceAttempts to fetch.
   */
  orderBy?: Prisma.SourceAttemptOrderByWithRelationInput | Prisma.SourceAttemptOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SourceAttempts.
   */
  cursor?: Prisma.SourceAttemptWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SourceAttempts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SourceAttempts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SourceAttempts.
   */
  distinct?: Prisma.SourceAttemptScalarFieldEnum | Prisma.SourceAttemptScalarFieldEnum[]
}

/**
 * SourceAttempt findFirstOrThrow
 */
export type SourceAttemptFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SourceAttempt
   */
  select?: Prisma.SourceAttemptSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SourceAttempt
   */
  omit?: Prisma.SourceAttemptOmit<ExtArgs> | null
  /**
   * Filter, which SourceAttempt to fetch.
   */
  where?: Prisma.SourceAttemptWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SourceAttempts to fetch.
   */
  orderBy?: Prisma.SourceAttemptOrderByWithRelationInput | Prisma.SourceAttemptOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SourceAttempts.
   */
  cursor?: Prisma.SourceAttemptWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SourceAttempts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SourceAttempts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SourceAttempts.
   */
  distinct?: Prisma.SourceAttemptScalarFieldEnum | Prisma.SourceAttemptScalarFieldEnum[]
}

/**
 * SourceAttempt findMany
 */
export type SourceAttemptFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SourceAttempt
   */
  select?: Prisma.SourceAttemptSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SourceAttempt
   */
  omit?: Prisma.SourceAttemptOmit<ExtArgs> | null
  /**
   * Filter, which SourceAttempts to fetch.
   */
  where?: Prisma.SourceAttemptWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SourceAttempts to fetch.
   */
  orderBy?: Prisma.SourceAttemptOrderByWithRelationInput | Prisma.SourceAttemptOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing SourceAttempts.
   */
  cursor?: Prisma.SourceAttemptWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SourceAttempts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SourceAttempts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SourceAttempts.
   */
  distinct?: Prisma.SourceAttemptScalarFieldEnum | Prisma.SourceAttemptScalarFieldEnum[]
}

/**
 * SourceAttempt create
 */
export type SourceAttemptCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SourceAttempt
   */
  select?: Prisma.SourceAttemptSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SourceAttempt
   */
  omit?: Prisma.SourceAttemptOmit<ExtArgs> | null
  /**
   * The data needed to create a SourceAttempt.
   */
  data: Prisma.XOR<Prisma.SourceAttemptCreateInput, Prisma.SourceAttemptUncheckedCreateInput>
}

/**
 * SourceAttempt createMany
 */
export type SourceAttemptCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many SourceAttempts.
   */
  data: Prisma.SourceAttemptCreateManyInput | Prisma.SourceAttemptCreateManyInput[]
}

/**
 * SourceAttempt createManyAndReturn
 */
export type SourceAttemptCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SourceAttempt
   */
  select?: Prisma.SourceAttemptSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SourceAttempt
   */
  omit?: Prisma.SourceAttemptOmit<ExtArgs> | null
  /**
   * The data used to create many SourceAttempts.
   */
  data: Prisma.SourceAttemptCreateManyInput | Prisma.SourceAttemptCreateManyInput[]
}

/**
 * SourceAttempt update
 */
export type SourceAttemptUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SourceAttempt
   */
  select?: Prisma.SourceAttemptSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SourceAttempt
   */
  omit?: Prisma.SourceAttemptOmit<ExtArgs> | null
  /**
   * The data needed to update a SourceAttempt.
   */
  data: Prisma.XOR<Prisma.SourceAttemptUpdateInput, Prisma.SourceAttemptUncheckedUpdateInput>
  /**
   * Choose, which SourceAttempt to update.
   */
  where: Prisma.SourceAttemptWhereUniqueInput
}

/**
 * SourceAttempt updateMany
 */
export type SourceAttemptUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update SourceAttempts.
   */
  data: Prisma.XOR<Prisma.SourceAttemptUpdateManyMutationInput, Prisma.SourceAttemptUncheckedUpdateManyInput>
  /**
   * Filter which SourceAttempts to update
   */
  where?: Prisma.SourceAttemptWhereInput
  /**
   * Limit how many SourceAttempts to update.
   */
  limit?: number
}

/**
 * SourceAttempt updateManyAndReturn
 */
export type SourceAttemptUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SourceAttempt
   */
  select?: Prisma.SourceAttemptSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SourceAttempt
   */
  omit?: Prisma.SourceAttemptOmit<ExtArgs> | null
  /**
   * The data used to update SourceAttempts.
   */
  data: Prisma.XOR<Prisma.SourceAttemptUpdateManyMutationInput, Prisma.SourceAttemptUncheckedUpdateManyInput>
  /**
   * Filter which SourceAttempts to update
   */
  where?: Prisma.SourceAttemptWhereInput
  /**
   * Limit how many SourceAttempts to update.
   */
  limit?: number
}

/**
 * SourceAttempt upsert
 */
export type SourceAttemptUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SourceAttempt
   */
  select?: Prisma.SourceAttemptSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SourceAttempt
   */
  omit?: Prisma.SourceAttemptOmit<ExtArgs> | null
  /**
   * The filter to search for the SourceAttempt to update in case it exists.
   */
  where: Prisma.SourceAttemptWhereUniqueInput
  /**
   * In case the SourceAttempt found by the `where` argument doesn't exist, create a new SourceAttempt with this data.
   */
  create: Prisma.XOR<Prisma.SourceAttemptCreateInput, Prisma.SourceAttemptUncheckedCreateInput>
  /**
   * In case the SourceAttempt was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SourceAttemptUpdateInput, Prisma.SourceAttemptUncheckedUpdateInput>
}

/**
 * SourceAttempt delete
 */
export type SourceAttemptDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SourceAttempt
   */
  select?: Prisma.SourceAttemptSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SourceAttempt
   */
  omit?: Prisma.SourceAttemptOmit<ExtArgs> | null
  /**
   * Filter which SourceAttempt to delete.
   */
  where: Prisma.SourceAttemptWhereUniqueInput
}

/**
 * SourceAttempt deleteMany
 */
export type SourceAttemptDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SourceAttempts to delete
   */
  where?: Prisma.SourceAttemptWhereInput
  /**
   * Limit how many SourceAttempts to delete.
   */
  limit?: number
}

/**
 * SourceAttempt without action
 */
export type SourceAttemptDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SourceAttempt
   */
  select?: Prisma.SourceAttemptSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SourceAttempt
   */
  omit?: Prisma.SourceAttemptOmit<ExtArgs> | null
}
