
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `SourceSnapshot` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model SourceSnapshot
 * 
 */
export type SourceSnapshotModel = runtime.Types.Result.DefaultSelection<Prisma.$SourceSnapshotPayload>

export type AggregateSourceSnapshot = {
  _count: SourceSnapshotCountAggregateOutputType | null
  _avg: SourceSnapshotAvgAggregateOutputType | null
  _sum: SourceSnapshotSumAggregateOutputType | null
  _min: SourceSnapshotMinAggregateOutputType | null
  _max: SourceSnapshotMaxAggregateOutputType | null
}

export type SourceSnapshotAvgAggregateOutputType = {
  ruleCount: number | null
  isCurrent: number | null
}

export type SourceSnapshotSumAggregateOutputType = {
  ruleCount: number | null
  isCurrent: number | null
}

export type SourceSnapshotMinAggregateOutputType = {
  id: string | null
  source: string | null
  timestamp: Date | null
  contentHash: string | null
  ruleCount: number | null
  ruleSample: string | null
  etag: string | null
  isCurrent: number | null
}

export type SourceSnapshotMaxAggregateOutputType = {
  id: string | null
  source: string | null
  timestamp: Date | null
  contentHash: string | null
  ruleCount: number | null
  ruleSample: string | null
  etag: string | null
  isCurrent: number | null
}

export type SourceSnapshotCountAggregateOutputType = {
  id: number
  source: number
  timestamp: number
  contentHash: number
  ruleCount: number
  ruleSample: number
  etag: number
  isCurrent: number
  _all: number
}


export type SourceSnapshotAvgAggregateInputType = {
  ruleCount?: true
  isCurrent?: true
}

export type SourceSnapshotSumAggregateInputType = {
  ruleCount?: true
  isCurrent?: true
}

export type SourceSnapshotMinAggregateInputType = {
  id?: true
  source?: true
  timestamp?: true
  contentHash?: true
  ruleCount?: true
  ruleSample?: true
  etag?: true
  isCurrent?: true
}

export type SourceSnapshotMaxAggregateInputType = {
  id?: true
  source?: true
  timestamp?: true
  contentHash?: true
  ruleCount?: true
  ruleSample?: true
  etag?: true
  isCurrent?: true
}

export type SourceSnapshotCountAggregateInputType = {
  id?: true
  source?: true
  timestamp?: true
  contentHash?: true
  ruleCount?: true
  ruleSample?: true
  etag?: true
  isCurrent?: true
  _all?: true
}

export type SourceSnapshotAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SourceSnapshot to aggregate.
   */
  where?: Prisma.SourceSnapshotWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SourceSnapshots to fetch.
   */
  orderBy?: Prisma.SourceSnapshotOrderByWithRelationInput | Prisma.SourceSnapshotOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SourceSnapshotWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SourceSnapshots from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SourceSnapshots.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned SourceSnapshots
  **/
  _count?: true | SourceSnapshotCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: SourceSnapshotAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: SourceSnapshotSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SourceSnapshotMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SourceSnapshotMaxAggregateInputType
}

export type GetSourceSnapshotAggregateType<T extends SourceSnapshotAggregateArgs> = {
      [P in keyof T & keyof AggregateSourceSnapshot]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSourceSnapshot[P]>
    : Prisma.GetScalarType<T[P], AggregateSourceSnapshot[P]>
}




export type SourceSnapshotGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SourceSnapshotWhereInput
  orderBy?: Prisma.SourceSnapshotOrderByWithAggregationInput | Prisma.SourceSnapshotOrderByWithAggregationInput[]
  by: Prisma.SourceSnapshotScalarFieldEnum[] | Prisma.SourceSnapshotScalarFieldEnum
  having?: Prisma.SourceSnapshotScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SourceSnapshotCountAggregateInputType | true
  _avg?: SourceSnapshotAvgAggregateInputType
  _sum?: SourceSnapshotSumAggregateInputType
  _min?: SourceSnapshotMinAggregateInputType
  _max?: SourceSnapshotMaxAggregateInputType
}

export type SourceSnapshotGroupByOutputType = {
  id: string
  source: string
  timestamp: Date
  contentHash: string
  ruleCount: number
  ruleSample: string | null
  etag: string | null
  isCurrent: number
  _count: SourceSnapshotCountAggregateOutputType | null
  _avg: SourceSnapshotAvgAggregateOutputType | null
  _sum: SourceSnapshotSumAggregateOutputType | null
  _min: SourceSnapshotMinAggregateOutputType | null
  _max: SourceSnapshotMaxAggregateOutputType | null
}

type GetSourceSnapshotGroupByPayload<T extends SourceSnapshotGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SourceSnapshotGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SourceSnapshotGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SourceSnapshotGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SourceSnapshotGroupByOutputType[P]>
      }
    >
  >



export type SourceSnapshotWhereInput = {
  AND?: Prisma.SourceSnapshotWhereInput | Prisma.SourceSnapshotWhereInput[]
  OR?: Prisma.SourceSnapshotWhereInput[]
  NOT?: Prisma.SourceSnapshotWhereInput | Prisma.SourceSnapshotWhereInput[]
  id?: Prisma.StringFilter<"SourceSnapshot"> | string
  source?: Prisma.StringFilter<"SourceSnapshot"> | string
  timestamp?: Prisma.DateTimeFilter<"SourceSnapshot"> | Date | string
  contentHash?: Prisma.StringFilter<"SourceSnapshot"> | string
  ruleCount?: Prisma.IntFilter<"SourceSnapshot"> | number
  ruleSample?: Prisma.StringNullableFilter<"SourceSnapshot"> | string | null
  etag?: Prisma.StringNullableFilter<"SourceSnapshot"> | string | null
  isCurrent?: Prisma.IntFilter<"SourceSnapshot"> | number
}

export type SourceSnapshotOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  source?: Prisma.SortOrder
  timestamp?: Prisma.SortOrder
  contentHash?: Prisma.SortOrder
  ruleCount?: Prisma.SortOrder
  ruleSample?: Prisma.SortOrderInput | Prisma.SortOrder
  etag?: Prisma.SortOrderInput | Prisma.SortOrder
  isCurrent?: Prisma.SortOrder
}

export type SourceSnapshotWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  source_isCurrent?: Prisma.SourceSnapshotSourceIsCurrentCompoundUniqueInput
  AND?: Prisma.SourceSnapshotWhereInput | Prisma.SourceSnapshotWhereInput[]
  OR?: Prisma.SourceSnapshotWhereInput[]
  NOT?: Prisma.SourceSnapshotWhereInput | Prisma.SourceSnapshotWhereInput[]
  source?: Prisma.StringFilter<"SourceSnapshot"> | string
  timestamp?: Prisma.DateTimeFilter<"SourceSnapshot"> | Date | string
  contentHash?: Prisma.StringFilter<"SourceSnapshot"> | string
  ruleCount?: Prisma.IntFilter<"SourceSnapshot"> | number
  ruleSample?: Prisma.StringNullableFilter<"SourceSnapshot"> | string | null
  etag?: Prisma.StringNullableFilter<"SourceSnapshot"> | string | null
  isCurrent?: Prisma.IntFilter<"SourceSnapshot"> | number
}, "id" | "source_isCurrent">

export type SourceSnapshotOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  source?: Prisma.SortOrder
  timestamp?: Prisma.SortOrder
  contentHash?: Prisma.SortOrder
  ruleCount?: Prisma.SortOrder
  ruleSample?: Prisma.SortOrderInput | Prisma.SortOrder
  etag?: Prisma.SortOrderInput | Prisma.SortOrder
  isCurrent?: Prisma.SortOrder
  _count?: Prisma.SourceSnapshotCountOrderByAggregateInput
  _avg?: Prisma.SourceSnapshotAvgOrderByAggregateInput
  _max?: Prisma.SourceSnapshotMaxOrderByAggregateInput
  _min?: Prisma.SourceSnapshotMinOrderByAggregateInput
  _sum?: Prisma.SourceSnapshotSumOrderByAggregateInput
}

export type SourceSnapshotScalarWhereWithAggregatesInput = {
  AND?: Prisma.SourceSnapshotScalarWhereWithAggregatesInput | Prisma.SourceSnapshotScalarWhereWithAggregatesInput[]
  OR?: Prisma.SourceSnapshotScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SourceSnapshotScalarWhereWithAggregatesInput | Prisma.SourceSnapshotScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"SourceSnapshot"> | string
  source?: Prisma.StringWithAggregatesFilter<"SourceSnapshot"> | string
  timestamp?: Prisma.DateTimeWithAggregatesFilter<"SourceSnapshot"> | Date | string
  contentHash?: Prisma.StringWithAggregatesFilter<"SourceSnapshot"> | string
  ruleCount?: Prisma.IntWithAggregatesFilter<"SourceSnapshot"> | number
  ruleSample?: Prisma.StringNullableWithAggregatesFilter<"SourceSnapshot"> | string | null
  etag?: Prisma.StringNullableWithAggregatesFilter<"SourceSnapshot"> | string | null
  isCurrent?: Prisma.IntWithAggregatesFilter<"SourceSnapshot"> | number
}

export type SourceSnapshotCreateInput = {
  id?: string
  source: string
  timestamp?: Date | string
  contentHash: string
  ruleCount: number
  ruleSample?: string | null
  etag?: string | null
  isCurrent?: number
}

export type SourceSnapshotUncheckedCreateInput = {
  id?: string
  source: string
  timestamp?: Date | string
  contentHash: string
  ruleCount: number
  ruleSample?: string | null
  etag?: string | null
  isCurrent?: number
}

export type SourceSnapshotUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  source?: Prisma.StringFieldUpdateOperationsInput | string
  timestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  contentHash?: Prisma.StringFieldUpdateOperationsInput | string
  ruleCount?: Prisma.IntFieldUpdateOperationsInput | number
  ruleSample?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  etag?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isCurrent?: Prisma.IntFieldUpdateOperationsInput | number
}

export type SourceSnapshotUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  source?: Prisma.StringFieldUpdateOperationsInput | string
  timestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  contentHash?: Prisma.StringFieldUpdateOperationsInput | string
  ruleCount?: Prisma.IntFieldUpdateOperationsInput | number
  ruleSample?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  etag?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isCurrent?: Prisma.IntFieldUpdateOperationsInput | number
}

export type SourceSnapshotCreateManyInput = {
  id?: string
  source: string
  timestamp?: Date | string
  contentHash: string
  ruleCount: number
  ruleSample?: string | null
  etag?: string | null
  isCurrent?: number
}

export type SourceSnapshotUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  source?: Prisma.StringFieldUpdateOperationsInput | string
  timestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  contentHash?: Prisma.StringFieldUpdateOperationsInput | string
  ruleCount?: Prisma.IntFieldUpdateOperationsInput | number
  ruleSample?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  etag?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isCurrent?: Prisma.IntFieldUpdateOperationsInput | number
}

export type SourceSnapshotUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  source?: Prisma.StringFieldUpdateOperationsInput | string
  timestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  contentHash?: Prisma.StringFieldUpdateOperationsInput | string
  ruleCount?: Prisma.IntFieldUpdateOperationsInput | number
  ruleSample?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  etag?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isCurrent?: Prisma.IntFieldUpdateOperationsInput | number
}

export type SourceSnapshotSourceIsCurrentCompoundUniqueInput = {
  source: string
  isCurrent: number
}

export type SourceSnapshotCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  source?: Prisma.SortOrder
  timestamp?: Prisma.SortOrder
  contentHash?: Prisma.SortOrder
  ruleCount?: Prisma.SortOrder
  ruleSample?: Prisma.SortOrder
  etag?: Prisma.SortOrder
  isCurrent?: Prisma.SortOrder
}

export type SourceSnapshotAvgOrderByAggregateInput = {
  ruleCount?: Prisma.SortOrder
  isCurrent?: Prisma.SortOrder
}

export type SourceSnapshotMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  source?: Prisma.SortOrder
  timestamp?: Prisma.SortOrder
  contentHash?: Prisma.SortOrder
  ruleCount?: Prisma.SortOrder
  ruleSample?: Prisma.SortOrder
  etag?: Prisma.SortOrder
  isCurrent?: Prisma.SortOrder
}

export type SourceSnapshotMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  source?: Prisma.SortOrder
  timestamp?: Prisma.SortOrder
  contentHash?: Prisma.SortOrder
  ruleCount?: Prisma.SortOrder
  ruleSample?: Prisma.SortOrder
  etag?: Prisma.SortOrder
  isCurrent?: Prisma.SortOrder
}

export type SourceSnapshotSumOrderByAggregateInput = {
  ruleCount?: Prisma.SortOrder
  isCurrent?: Prisma.SortOrder
}



export type SourceSnapshotSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  source?: boolean
  timestamp?: boolean
  contentHash?: boolean
  ruleCount?: boolean
  ruleSample?: boolean
  etag?: boolean
  isCurrent?: boolean
}, ExtArgs["result"]["sourceSnapshot"]>

export type SourceSnapshotSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  source?: boolean
  timestamp?: boolean
  contentHash?: boolean
  ruleCount?: boolean
  ruleSample?: boolean
  etag?: boolean
  isCurrent?: boolean
}, ExtArgs["result"]["sourceSnapshot"]>

export type SourceSnapshotSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  source?: boolean
  timestamp?: boolean
  contentHash?: boolean
  ruleCount?: boolean
  ruleSample?: boolean
  etag?: boolean
  isCurrent?: boolean
}, ExtArgs["result"]["sourceSnapshot"]>

export type SourceSnapshotSelectScalar = {
  id?: boolean
  source?: boolean
  timestamp?: boolean
  contentHash?: boolean
  ruleCount?: boolean
  ruleSample?: boolean
  etag?: boolean
  isCurrent?: boolean
}

export type SourceSnapshotOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "source" | "timestamp" | "contentHash" | "ruleCount" | "ruleSample" | "etag" | "isCurrent", ExtArgs["result"]["sourceSnapshot"]>

export type $SourceSnapshotPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "SourceSnapshot"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    source: string
    timestamp: Date
    contentHash: string
    ruleCount: number
    ruleSample: string | null
    etag: string | null
    isCurrent: number
  }, ExtArgs["result"]["sourceSnapshot"]>
  composites: {}
}

export type SourceSnapshotGetPayload<S extends boolean | null | undefined | SourceSnapshotDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SourceSnapshotPayload, S>

export type SourceSnapshotCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SourceSnapshotFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SourceSnapshotCountAggregateInputType | true
  }

export interface SourceSnapshotDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['SourceSnapshot'], meta: { name: 'SourceSnapshot' } }
  /**
   * Find zero or one SourceSnapshot that matches the filter.
   * @param {SourceSnapshotFindUniqueArgs} args - Arguments to find a SourceSnapshot
   * @example
   * // Get one SourceSnapshot
   * const sourceSnapshot = await prisma.sourceSnapshot.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SourceSnapshotFindUniqueArgs>(args: Prisma.SelectSubset<T, SourceSnapshotFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SourceSnapshotClient<runtime.Types.Result.GetResult<Prisma.$SourceSnapshotPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one SourceSnapshot that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SourceSnapshotFindUniqueOrThrowArgs} args - Arguments to find a SourceSnapshot
   * @example
   * // Get one SourceSnapshot
   * const sourceSnapshot = await prisma.sourceSnapshot.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SourceSnapshotFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SourceSnapshotFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SourceSnapshotClient<runtime.Types.Result.GetResult<Prisma.$SourceSnapshotPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SourceSnapshot that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SourceSnapshotFindFirstArgs} args - Arguments to find a SourceSnapshot
   * @example
   * // Get one SourceSnapshot
   * const sourceSnapshot = await prisma.sourceSnapshot.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SourceSnapshotFindFirstArgs>(args?: Prisma.SelectSubset<T, SourceSnapshotFindFirstArgs<ExtArgs>>): Prisma.Prisma__SourceSnapshotClient<runtime.Types.Result.GetResult<Prisma.$SourceSnapshotPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SourceSnapshot that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SourceSnapshotFindFirstOrThrowArgs} args - Arguments to find a SourceSnapshot
   * @example
   * // Get one SourceSnapshot
   * const sourceSnapshot = await prisma.sourceSnapshot.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SourceSnapshotFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SourceSnapshotFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SourceSnapshotClient<runtime.Types.Result.GetResult<Prisma.$SourceSnapshotPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more SourceSnapshots that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SourceSnapshotFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all SourceSnapshots
   * const sourceSnapshots = await prisma.sourceSnapshot.findMany()
   * 
   * // Get first 10 SourceSnapshots
   * const sourceSnapshots = await prisma.sourceSnapshot.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const sourceSnapshotWithIdOnly = await prisma.sourceSnapshot.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends SourceSnapshotFindManyArgs>(args?: Prisma.SelectSubset<T, SourceSnapshotFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SourceSnapshotPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a SourceSnapshot.
   * @param {SourceSnapshotCreateArgs} args - Arguments to create a SourceSnapshot.
   * @example
   * // Create one SourceSnapshot
   * const SourceSnapshot = await prisma.sourceSnapshot.create({
   *   data: {
   *     // ... data to create a SourceSnapshot
   *   }
   * })
   * 
   */
  create<T extends SourceSnapshotCreateArgs>(args: Prisma.SelectSubset<T, SourceSnapshotCreateArgs<ExtArgs>>): Prisma.Prisma__SourceSnapshotClient<runtime.Types.Result.GetResult<Prisma.$SourceSnapshotPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many SourceSnapshots.
   * @param {SourceSnapshotCreateManyArgs} args - Arguments to create many SourceSnapshots.
   * @example
   * // Create many SourceSnapshots
   * const sourceSnapshot = await prisma.sourceSnapshot.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SourceSnapshotCreateManyArgs>(args?: Prisma.SelectSubset<T, SourceSnapshotCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many SourceSnapshots and returns the data saved in the database.
   * @param {SourceSnapshotCreateManyAndReturnArgs} args - Arguments to create many SourceSnapshots.
   * @example
   * // Create many SourceSnapshots
   * const sourceSnapshot = await prisma.sourceSnapshot.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many SourceSnapshots and only return the `id`
   * const sourceSnapshotWithIdOnly = await prisma.sourceSnapshot.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends SourceSnapshotCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, SourceSnapshotCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SourceSnapshotPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a SourceSnapshot.
   * @param {SourceSnapshotDeleteArgs} args - Arguments to delete one SourceSnapshot.
   * @example
   * // Delete one SourceSnapshot
   * const SourceSnapshot = await prisma.sourceSnapshot.delete({
   *   where: {
   *     // ... filter to delete one SourceSnapshot
   *   }
   * })
   * 
   */
  delete<T extends SourceSnapshotDeleteArgs>(args: Prisma.SelectSubset<T, SourceSnapshotDeleteArgs<ExtArgs>>): Prisma.Prisma__SourceSnapshotClient<runtime.Types.Result.GetResult<Prisma.$SourceSnapshotPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one SourceSnapshot.
   * @param {SourceSnapshotUpdateArgs} args - Arguments to update one SourceSnapshot.
   * @example
   * // Update one SourceSnapshot
   * const sourceSnapshot = await prisma.sourceSnapshot.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SourceSnapshotUpdateArgs>(args: Prisma.SelectSubset<T, SourceSnapshotUpdateArgs<ExtArgs>>): Prisma.Prisma__SourceSnapshotClient<runtime.Types.Result.GetResult<Prisma.$SourceSnapshotPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more SourceSnapshots.
   * @param {SourceSnapshotDeleteManyArgs} args - Arguments to filter SourceSnapshots to delete.
   * @example
   * // Delete a few SourceSnapshots
   * const { count } = await prisma.sourceSnapshot.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SourceSnapshotDeleteManyArgs>(args?: Prisma.SelectSubset<T, SourceSnapshotDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SourceSnapshots.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SourceSnapshotUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many SourceSnapshots
   * const sourceSnapshot = await prisma.sourceSnapshot.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SourceSnapshotUpdateManyArgs>(args: Prisma.SelectSubset<T, SourceSnapshotUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SourceSnapshots and returns the data updated in the database.
   * @param {SourceSnapshotUpdateManyAndReturnArgs} args - Arguments to update many SourceSnapshots.
   * @example
   * // Update many SourceSnapshots
   * const sourceSnapshot = await prisma.sourceSnapshot.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more SourceSnapshots and only return the `id`
   * const sourceSnapshotWithIdOnly = await prisma.sourceSnapshot.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends SourceSnapshotUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, SourceSnapshotUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SourceSnapshotPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one SourceSnapshot.
   * @param {SourceSnapshotUpsertArgs} args - Arguments to update or create a SourceSnapshot.
   * @example
   * // Update or create a SourceSnapshot
   * const sourceSnapshot = await prisma.sourceSnapshot.upsert({
   *   create: {
   *     // ... data to create a SourceSnapshot
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the SourceSnapshot we want to update
   *   }
   * })
   */
  upsert<T extends SourceSnapshotUpsertArgs>(args: Prisma.SelectSubset<T, SourceSnapshotUpsertArgs<ExtArgs>>): Prisma.Prisma__SourceSnapshotClient<runtime.Types.Result.GetResult<Prisma.$SourceSnapshotPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of SourceSnapshots.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SourceSnapshotCountArgs} args - Arguments to filter SourceSnapshots to count.
   * @example
   * // Count the number of SourceSnapshots
   * const count = await prisma.sourceSnapshot.count({
   *   where: {
   *     // ... the filter for the SourceSnapshots we want to count
   *   }
   * })
  **/
  count<T extends SourceSnapshotCountArgs>(
    args?: Prisma.Subset<T, SourceSnapshotCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SourceSnapshotCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a SourceSnapshot.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SourceSnapshotAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SourceSnapshotAggregateArgs>(args: Prisma.Subset<T, SourceSnapshotAggregateArgs>): Prisma.PrismaPromise<GetSourceSnapshotAggregateType<T>>

  /**
   * Group by SourceSnapshot.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SourceSnapshotGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SourceSnapshotGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SourceSnapshotGroupByArgs['orderBy'] }
      : { orderBy?: SourceSnapshotGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SourceSnapshotGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSourceSnapshotGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the SourceSnapshot model
 */
readonly fields: SourceSnapshotFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for SourceSnapshot.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SourceSnapshotClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the SourceSnapshot model
 */
export interface SourceSnapshotFieldRefs {
  readonly id: Prisma.FieldRef<"SourceSnapshot", 'String'>
  readonly source: Prisma.FieldRef<"SourceSnapshot", 'String'>
  readonly timestamp: Prisma.FieldRef<"SourceSnapshot", 'DateTime'>
  readonly contentHash: Prisma.FieldRef<"SourceSnapshot", 'String'>
  readonly ruleCount: Prisma.FieldRef<"SourceSnapshot", 'Int'>
  readonly ruleSample: Prisma.FieldRef<"SourceSnapshot", 'String'>
  readonly etag: Prisma.FieldRef<"SourceSnapshot", 'String'>
  readonly isCurrent: Prisma.FieldRef<"SourceSnapshot", 'Int'>
}
    

// Custom InputTypes
/**
 * SourceSnapshot findUnique
 */
export type SourceSnapshotFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SourceSnapshot
   */
  select?: Prisma.SourceSnapshotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SourceSnapshot
   */
  omit?: Prisma.SourceSnapshotOmit<ExtArgs> | null
  /**
   * Filter, which SourceSnapshot to fetch.
   */
  where: Prisma.SourceSnapshotWhereUniqueInput
}

/**
 * SourceSnapshot findUniqueOrThrow
 */
export type SourceSnapshotFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SourceSnapshot
   */
  select?: Prisma.SourceSnapshotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SourceSnapshot
   */
  omit?: Prisma.SourceSnapshotOmit<ExtArgs> | null
  /**
   * Filter, which SourceSnapshot to fetch.
   */
  where: Prisma.SourceSnapshotWhereUniqueInput
}

/**
 * SourceSnapshot findFirst
 */
export type SourceSnapshotFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SourceSnapshot
   */
  select?: Prisma.SourceSnapshotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SourceSnapshot
   */
  omit?: Prisma.SourceSnapshotOmit<ExtArgs> | null
  /**
   * Filter, which SourceSnapshot to fetch.
   */
  where?: Prisma.SourceSnapshotWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SourceSnapshots to fetch.
   */
  orderBy?: Prisma.SourceSnapshotOrderByWithRelationInput | Prisma.SourceSnapshotOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SourceSnapshots.
   */
  cursor?: Prisma.SourceSnapshotWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SourceSnapshots from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SourceSnapshots.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SourceSnapshots.
   */
  distinct?: Prisma.SourceSnapshotScalarFieldEnum | Prisma.SourceSnapshotScalarFieldEnum[]
}

/**
 * SourceSnapshot findFirstOrThrow
 */
export type SourceSnapshotFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SourceSnapshot
   */
  select?: Prisma.SourceSnapshotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SourceSnapshot
   */
  omit?: Prisma.SourceSnapshotOmit<ExtArgs> | null
  /**
   * Filter, which SourceSnapshot to fetch.
   */
  where?: Prisma.SourceSnapshotWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SourceSnapshots to fetch.
   */
  orderBy?: Prisma.SourceSnapshotOrderByWithRelationInput | Prisma.SourceSnapshotOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SourceSnapshots.
   */
  cursor?: Prisma.SourceSnapshotWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SourceSnapshots from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SourceSnapshots.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SourceSnapshots.
   */
  distinct?: Prisma.SourceSnapshotScalarFieldEnum | Prisma.SourceSnapshotScalarFieldEnum[]
}

/**
 * SourceSnapshot findMany
 */
export type SourceSnapshotFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SourceSnapshot
   */
  select?: Prisma.SourceSnapshotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SourceSnapshot
   */
  omit?: Prisma.SourceSnapshotOmit<ExtArgs> | null
  /**
   * Filter, which SourceSnapshots to fetch.
   */
  where?: Prisma.SourceSnapshotWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SourceSnapshots to fetch.
   */
  orderBy?: Prisma.SourceSnapshotOrderByWithRelationInput | Prisma.SourceSnapshotOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing SourceSnapshots.
   */
  cursor?: Prisma.SourceSnapshotWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SourceSnapshots from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SourceSnapshots.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SourceSnapshots.
   */
  distinct?: Prisma.SourceSnapshotScalarFieldEnum | Prisma.SourceSnapshotScalarFieldEnum[]
}

/**
 * SourceSnapshot create
 */
export type SourceSnapshotCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SourceSnapshot
   */
  select?: Prisma.SourceSnapshotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SourceSnapshot
   */
  omit?: Prisma.SourceSnapshotOmit<ExtArgs> | null
  /**
   * The data needed to create a SourceSnapshot.
   */
  data: Prisma.XOR<Prisma.SourceSnapshotCreateInput, Prisma.SourceSnapshotUncheckedCreateInput>
}

/**
 * SourceSnapshot createMany
 */
export type SourceSnapshotCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many SourceSnapshots.
   */
  data: Prisma.SourceSnapshotCreateManyInput | Prisma.SourceSnapshotCreateManyInput[]
}

/**
 * SourceSnapshot createManyAndReturn
 */
export type SourceSnapshotCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SourceSnapshot
   */
  select?: Prisma.SourceSnapshotSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SourceSnapshot
   */
  omit?: Prisma.SourceSnapshotOmit<ExtArgs> | null
  /**
   * The data used to create many SourceSnapshots.
   */
  data: Prisma.SourceSnapshotCreateManyInput | Prisma.SourceSnapshotCreateManyInput[]
}

/**
 * SourceSnapshot update
 */
export type SourceSnapshotUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SourceSnapshot
   */
  select?: Prisma.SourceSnapshotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SourceSnapshot
   */
  omit?: Prisma.SourceSnapshotOmit<ExtArgs> | null
  /**
   * The data needed to update a SourceSnapshot.
   */
  data: Prisma.XOR<Prisma.SourceSnapshotUpdateInput, Prisma.SourceSnapshotUncheckedUpdateInput>
  /**
   * Choose, which SourceSnapshot to update.
   */
  where: Prisma.SourceSnapshotWhereUniqueInput
}

/**
 * SourceSnapshot updateMany
 */
export type SourceSnapshotUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update SourceSnapshots.
   */
  data: Prisma.XOR<Prisma.SourceSnapshotUpdateManyMutationInput, Prisma.SourceSnapshotUncheckedUpdateManyInput>
  /**
   * Filter which SourceSnapshots to update
   */
  where?: Prisma.SourceSnapshotWhereInput
  /**
   * Limit how many SourceSnapshots to update.
   */
  limit?: number
}

/**
 * SourceSnapshot updateManyAndReturn
 */
export type SourceSnapshotUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SourceSnapshot
   */
  select?: Prisma.SourceSnapshotSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SourceSnapshot
   */
  omit?: Prisma.SourceSnapshotOmit<ExtArgs> | null
  /**
   * The data used to update SourceSnapshots.
   */
  data: Prisma.XOR<Prisma.SourceSnapshotUpdateManyMutationInput, Prisma.SourceSnapshotUncheckedUpdateManyInput>
  /**
   * Filter which SourceSnapshots to update
   */
  where?: Prisma.SourceSnapshotWhereInput
  /**
   * Limit how many SourceSnapshots to update.
   */
  limit?: number
}

/**
 * SourceSnapshot upsert
 */
export type SourceSnapshotUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SourceSnapshot
   */
  select?: Prisma.SourceSnapshotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SourceSnapshot
   */
  omit?: Prisma.SourceSnapshotOmit<ExtArgs> | null
  /**
   * The filter to search for the SourceSnapshot to update in case it exists.
   */
  where: Prisma.SourceSnapshotWhereUniqueInput
  /**
   * In case the SourceSnapshot found by the `where` argument doesn't exist, create a new SourceSnapshot with this data.
   */
  create: Prisma.XOR<Prisma.SourceSnapshotCreateInput, Prisma.SourceSnapshotUncheckedCreateInput>
  /**
   * In case the SourceSnapshot was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SourceSnapshotUpdateInput, Prisma.SourceSnapshotUncheckedUpdateInput>
}

/**
 * SourceSnapshot delete
 */
export type SourceSnapshotDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SourceSnapshot
   */
  select?: Prisma.SourceSnapshotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SourceSnapshot
   */
  omit?: Prisma.SourceSnapshotOmit<ExtArgs> | null
  /**
   * Filter which SourceSnapshot to delete.
   */
  where: Prisma.SourceSnapshotWhereUniqueInput
}

/**
 * SourceSnapshot deleteMany
 */
export type SourceSnapshotDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SourceSnapshots to delete
   */
  where?: Prisma.SourceSnapshotWhereInput
  /**
   * Limit how many SourceSnapshots to delete.
   */
  limit?: number
}

/**
 * SourceSnapshot without action
 */
export type SourceSnapshotDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SourceSnapshot
   */
  select?: Prisma.SourceSnapshotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SourceSnapshot
   */
  omit?: Prisma.SourceSnapshotOmit<ExtArgs> | null
}
