
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `StorageEntry` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model StorageEntry
 * 
 */
export type StorageEntryModel = runtime.Types.Result.DefaultSelection<Prisma.$StorageEntryPayload>

export type AggregateStorageEntry = {
  _count: StorageEntryCountAggregateOutputType | null
  _min: StorageEntryMinAggregateOutputType | null
  _max: StorageEntryMaxAggregateOutputType | null
}

export type StorageEntryMinAggregateOutputType = {
  id: string | null
  key: string | null
  data: string | null
  createdAt: Date | null
  updatedAt: Date | null
  expiresAt: Date | null
  tags: string | null
}

export type StorageEntryMaxAggregateOutputType = {
  id: string | null
  key: string | null
  data: string | null
  createdAt: Date | null
  updatedAt: Date | null
  expiresAt: Date | null
  tags: string | null
}

export type StorageEntryCountAggregateOutputType = {
  id: number
  key: number
  data: number
  createdAt: number
  updatedAt: number
  expiresAt: number
  tags: number
  _all: number
}


export type StorageEntryMinAggregateInputType = {
  id?: true
  key?: true
  data?: true
  createdAt?: true
  updatedAt?: true
  expiresAt?: true
  tags?: true
}

export type StorageEntryMaxAggregateInputType = {
  id?: true
  key?: true
  data?: true
  createdAt?: true
  updatedAt?: true
  expiresAt?: true
  tags?: true
}

export type StorageEntryCountAggregateInputType = {
  id?: true
  key?: true
  data?: true
  createdAt?: true
  updatedAt?: true
  expiresAt?: true
  tags?: true
  _all?: true
}

export type StorageEntryAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which StorageEntry to aggregate.
   */
  where?: Prisma.StorageEntryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of StorageEntries to fetch.
   */
  orderBy?: Prisma.StorageEntryOrderByWithRelationInput | Prisma.StorageEntryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.StorageEntryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` StorageEntries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` StorageEntries.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned StorageEntries
  **/
  _count?: true | StorageEntryCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: StorageEntryMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: StorageEntryMaxAggregateInputType
}

export type GetStorageEntryAggregateType<T extends StorageEntryAggregateArgs> = {
      [P in keyof T & keyof AggregateStorageEntry]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateStorageEntry[P]>
    : Prisma.GetScalarType<T[P], AggregateStorageEntry[P]>
}




export type StorageEntryGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.StorageEntryWhereInput
  orderBy?: Prisma.StorageEntryOrderByWithAggregationInput | Prisma.StorageEntryOrderByWithAggregationInput[]
  by: Prisma.StorageEntryScalarFieldEnum[] | Prisma.StorageEntryScalarFieldEnum
  having?: Prisma.StorageEntryScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: StorageEntryCountAggregateInputType | true
  _min?: StorageEntryMinAggregateInputType
  _max?: StorageEntryMaxAggregateInputType
}

export type StorageEntryGroupByOutputType = {
  id: string
  key: string
  data: string
  createdAt: Date
  updatedAt: Date
  expiresAt: Date | null
  tags: string | null
  _count: StorageEntryCountAggregateOutputType | null
  _min: StorageEntryMinAggregateOutputType | null
  _max: StorageEntryMaxAggregateOutputType | null
}

type GetStorageEntryGroupByPayload<T extends StorageEntryGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<StorageEntryGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof StorageEntryGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], StorageEntryGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], StorageEntryGroupByOutputType[P]>
      }
    >
  >



export type StorageEntryWhereInput = {
  AND?: Prisma.StorageEntryWhereInput | Prisma.StorageEntryWhereInput[]
  OR?: Prisma.StorageEntryWhereInput[]
  NOT?: Prisma.StorageEntryWhereInput | Prisma.StorageEntryWhereInput[]
  id?: Prisma.StringFilter<"StorageEntry"> | string
  key?: Prisma.StringFilter<"StorageEntry"> | string
  data?: Prisma.StringFilter<"StorageEntry"> | string
  createdAt?: Prisma.DateTimeFilter<"StorageEntry"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"StorageEntry"> | Date | string
  expiresAt?: Prisma.DateTimeNullableFilter<"StorageEntry"> | Date | string | null
  tags?: Prisma.StringNullableFilter<"StorageEntry"> | string | null
}

export type StorageEntryOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  key?: Prisma.SortOrder
  data?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrderInput | Prisma.SortOrder
  tags?: Prisma.SortOrderInput | Prisma.SortOrder
}

export type StorageEntryWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  key?: string
  AND?: Prisma.StorageEntryWhereInput | Prisma.StorageEntryWhereInput[]
  OR?: Prisma.StorageEntryWhereInput[]
  NOT?: Prisma.StorageEntryWhereInput | Prisma.StorageEntryWhereInput[]
  data?: Prisma.StringFilter<"StorageEntry"> | string
  createdAt?: Prisma.DateTimeFilter<"StorageEntry"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"StorageEntry"> | Date | string
  expiresAt?: Prisma.DateTimeNullableFilter<"StorageEntry"> | Date | string | null
  tags?: Prisma.StringNullableFilter<"StorageEntry"> | string | null
}, "id" | "key">

export type StorageEntryOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  key?: Prisma.SortOrder
  data?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrderInput | Prisma.SortOrder
  tags?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.StorageEntryCountOrderByAggregateInput
  _max?: Prisma.StorageEntryMaxOrderByAggregateInput
  _min?: Prisma.StorageEntryMinOrderByAggregateInput
}

export type StorageEntryScalarWhereWithAggregatesInput = {
  AND?: Prisma.StorageEntryScalarWhereWithAggregatesInput | Prisma.StorageEntryScalarWhereWithAggregatesInput[]
  OR?: Prisma.StorageEntryScalarWhereWithAggregatesInput[]
  NOT?: Prisma.StorageEntryScalarWhereWithAggregatesInput | Prisma.StorageEntryScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"StorageEntry"> | string
  key?: Prisma.StringWithAggregatesFilter<"StorageEntry"> | string
  data?: Prisma.StringWithAggregatesFilter<"StorageEntry"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"StorageEntry"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"StorageEntry"> | Date | string
  expiresAt?: Prisma.DateTimeNullableWithAggregatesFilter<"StorageEntry"> | Date | string | null
  tags?: Prisma.StringNullableWithAggregatesFilter<"StorageEntry"> | string | null
}

export type StorageEntryCreateInput = {
  id?: string
  key: string
  data: string
  createdAt?: Date | string
  updatedAt?: Date | string
  expiresAt?: Date | string | null
  tags?: string | null
}

export type StorageEntryUncheckedCreateInput = {
  id?: string
  key: string
  data: string
  createdAt?: Date | string
  updatedAt?: Date | string
  expiresAt?: Date | string | null
  tags?: string | null
}

export type StorageEntryUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  data?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  tags?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type StorageEntryUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  data?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  tags?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type StorageEntryCreateManyInput = {
  id?: string
  key: string
  data: string
  createdAt?: Date | string
  updatedAt?: Date | string
  expiresAt?: Date | string | null
  tags?: string | null
}

export type StorageEntryUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  data?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  tags?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type StorageEntryUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  data?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  expiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  tags?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type StorageEntryCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  key?: Prisma.SortOrder
  data?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
  tags?: Prisma.SortOrder
}

export type StorageEntryMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  key?: Prisma.SortOrder
  data?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
  tags?: Prisma.SortOrder
}

export type StorageEntryMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  key?: Prisma.SortOrder
  data?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
  tags?: Prisma.SortOrder
}



export type StorageEntrySelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  key?: boolean
  data?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  expiresAt?: boolean
  tags?: boolean
}, ExtArgs["result"]["storageEntry"]>

export type StorageEntrySelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  key?: boolean
  data?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  expiresAt?: boolean
  tags?: boolean
}, ExtArgs["result"]["storageEntry"]>

export type StorageEntrySelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  key?: boolean
  data?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  expiresAt?: boolean
  tags?: boolean
}, ExtArgs["result"]["storageEntry"]>

export type StorageEntrySelectScalar = {
  id?: boolean
  key?: boolean
  data?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  expiresAt?: boolean
  tags?: boolean
}

export type StorageEntryOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "key" | "data" | "createdAt" | "updatedAt" | "expiresAt" | "tags", ExtArgs["result"]["storageEntry"]>

export type $StorageEntryPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "StorageEntry"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    key: string
    data: string
    createdAt: Date
    updatedAt: Date
    expiresAt: Date | null
    tags: string | null
  }, ExtArgs["result"]["storageEntry"]>
  composites: {}
}

export type StorageEntryGetPayload<S extends boolean | null | undefined | StorageEntryDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$StorageEntryPayload, S>

export type StorageEntryCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<StorageEntryFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: StorageEntryCountAggregateInputType | true
  }

export interface StorageEntryDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['StorageEntry'], meta: { name: 'StorageEntry' } }
  /**
   * Find zero or one StorageEntry that matches the filter.
   * @param {StorageEntryFindUniqueArgs} args - Arguments to find a StorageEntry
   * @example
   * // Get one StorageEntry
   * const storageEntry = await prisma.storageEntry.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends StorageEntryFindUniqueArgs>(args: Prisma.SelectSubset<T, StorageEntryFindUniqueArgs<ExtArgs>>): Prisma.Prisma__StorageEntryClient<runtime.Types.Result.GetResult<Prisma.$StorageEntryPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one StorageEntry that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {StorageEntryFindUniqueOrThrowArgs} args - Arguments to find a StorageEntry
   * @example
   * // Get one StorageEntry
   * const storageEntry = await prisma.storageEntry.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends StorageEntryFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, StorageEntryFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__StorageEntryClient<runtime.Types.Result.GetResult<Prisma.$StorageEntryPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first StorageEntry that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StorageEntryFindFirstArgs} args - Arguments to find a StorageEntry
   * @example
   * // Get one StorageEntry
   * const storageEntry = await prisma.storageEntry.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends StorageEntryFindFirstArgs>(args?: Prisma.SelectSubset<T, StorageEntryFindFirstArgs<ExtArgs>>): Prisma.Prisma__StorageEntryClient<runtime.Types.Result.GetResult<Prisma.$StorageEntryPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first StorageEntry that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StorageEntryFindFirstOrThrowArgs} args - Arguments to find a StorageEntry
   * @example
   * // Get one StorageEntry
   * const storageEntry = await prisma.storageEntry.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends StorageEntryFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, StorageEntryFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__StorageEntryClient<runtime.Types.Result.GetResult<Prisma.$StorageEntryPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more StorageEntries that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StorageEntryFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all StorageEntries
   * const storageEntries = await prisma.storageEntry.findMany()
   * 
   * // Get first 10 StorageEntries
   * const storageEntries = await prisma.storageEntry.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const storageEntryWithIdOnly = await prisma.storageEntry.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends StorageEntryFindManyArgs>(args?: Prisma.SelectSubset<T, StorageEntryFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StorageEntryPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a StorageEntry.
   * @param {StorageEntryCreateArgs} args - Arguments to create a StorageEntry.
   * @example
   * // Create one StorageEntry
   * const StorageEntry = await prisma.storageEntry.create({
   *   data: {
   *     // ... data to create a StorageEntry
   *   }
   * })
   * 
   */
  create<T extends StorageEntryCreateArgs>(args: Prisma.SelectSubset<T, StorageEntryCreateArgs<ExtArgs>>): Prisma.Prisma__StorageEntryClient<runtime.Types.Result.GetResult<Prisma.$StorageEntryPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many StorageEntries.
   * @param {StorageEntryCreateManyArgs} args - Arguments to create many StorageEntries.
   * @example
   * // Create many StorageEntries
   * const storageEntry = await prisma.storageEntry.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends StorageEntryCreateManyArgs>(args?: Prisma.SelectSubset<T, StorageEntryCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many StorageEntries and returns the data saved in the database.
   * @param {StorageEntryCreateManyAndReturnArgs} args - Arguments to create many StorageEntries.
   * @example
   * // Create many StorageEntries
   * const storageEntry = await prisma.storageEntry.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many StorageEntries and only return the `id`
   * const storageEntryWithIdOnly = await prisma.storageEntry.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends StorageEntryCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, StorageEntryCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StorageEntryPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a StorageEntry.
   * @param {StorageEntryDeleteArgs} args - Arguments to delete one StorageEntry.
   * @example
   * // Delete one StorageEntry
   * const StorageEntry = await prisma.storageEntry.delete({
   *   where: {
   *     // ... filter to delete one StorageEntry
   *   }
   * })
   * 
   */
  delete<T extends StorageEntryDeleteArgs>(args: Prisma.SelectSubset<T, StorageEntryDeleteArgs<ExtArgs>>): Prisma.Prisma__StorageEntryClient<runtime.Types.Result.GetResult<Prisma.$StorageEntryPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one StorageEntry.
   * @param {StorageEntryUpdateArgs} args - Arguments to update one StorageEntry.
   * @example
   * // Update one StorageEntry
   * const storageEntry = await prisma.storageEntry.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends StorageEntryUpdateArgs>(args: Prisma.SelectSubset<T, StorageEntryUpdateArgs<ExtArgs>>): Prisma.Prisma__StorageEntryClient<runtime.Types.Result.GetResult<Prisma.$StorageEntryPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more StorageEntries.
   * @param {StorageEntryDeleteManyArgs} args - Arguments to filter StorageEntries to delete.
   * @example
   * // Delete a few StorageEntries
   * const { count } = await prisma.storageEntry.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends StorageEntryDeleteManyArgs>(args?: Prisma.SelectSubset<T, StorageEntryDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more StorageEntries.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StorageEntryUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many StorageEntries
   * const storageEntry = await prisma.storageEntry.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends StorageEntryUpdateManyArgs>(args: Prisma.SelectSubset<T, StorageEntryUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more StorageEntries and returns the data updated in the database.
   * @param {StorageEntryUpdateManyAndReturnArgs} args - Arguments to update many StorageEntries.
   * @example
   * // Update many StorageEntries
   * const storageEntry = await prisma.storageEntry.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more StorageEntries and only return the `id`
   * const storageEntryWithIdOnly = await prisma.storageEntry.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends StorageEntryUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, StorageEntryUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StorageEntryPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one StorageEntry.
   * @param {StorageEntryUpsertArgs} args - Arguments to update or create a StorageEntry.
   * @example
   * // Update or create a StorageEntry
   * const storageEntry = await prisma.storageEntry.upsert({
   *   create: {
   *     // ... data to create a StorageEntry
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the StorageEntry we want to update
   *   }
   * })
   */
  upsert<T extends StorageEntryUpsertArgs>(args: Prisma.SelectSubset<T, StorageEntryUpsertArgs<ExtArgs>>): Prisma.Prisma__StorageEntryClient<runtime.Types.Result.GetResult<Prisma.$StorageEntryPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of StorageEntries.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StorageEntryCountArgs} args - Arguments to filter StorageEntries to count.
   * @example
   * // Count the number of StorageEntries
   * const count = await prisma.storageEntry.count({
   *   where: {
   *     // ... the filter for the StorageEntries we want to count
   *   }
   * })
  **/
  count<T extends StorageEntryCountArgs>(
    args?: Prisma.Subset<T, StorageEntryCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], StorageEntryCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a StorageEntry.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StorageEntryAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends StorageEntryAggregateArgs>(args: Prisma.Subset<T, StorageEntryAggregateArgs>): Prisma.PrismaPromise<GetStorageEntryAggregateType<T>>

  /**
   * Group by StorageEntry.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StorageEntryGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends StorageEntryGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: StorageEntryGroupByArgs['orderBy'] }
      : { orderBy?: StorageEntryGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, StorageEntryGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetStorageEntryGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the StorageEntry model
 */
readonly fields: StorageEntryFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for StorageEntry.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__StorageEntryClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the StorageEntry model
 */
export interface StorageEntryFieldRefs {
  readonly id: Prisma.FieldRef<"StorageEntry", 'String'>
  readonly key: Prisma.FieldRef<"StorageEntry", 'String'>
  readonly data: Prisma.FieldRef<"StorageEntry", 'String'>
  readonly createdAt: Prisma.FieldRef<"StorageEntry", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"StorageEntry", 'DateTime'>
  readonly expiresAt: Prisma.FieldRef<"StorageEntry", 'DateTime'>
  readonly tags: Prisma.FieldRef<"StorageEntry", 'String'>
}
    

// Custom InputTypes
/**
 * StorageEntry findUnique
 */
export type StorageEntryFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StorageEntry
   */
  select?: Prisma.StorageEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the StorageEntry
   */
  omit?: Prisma.StorageEntryOmit<ExtArgs> | null
  /**
   * Filter, which StorageEntry to fetch.
   */
  where: Prisma.StorageEntryWhereUniqueInput
}

/**
 * StorageEntry findUniqueOrThrow
 */
export type StorageEntryFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StorageEntry
   */
  select?: Prisma.StorageEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the StorageEntry
   */
  omit?: Prisma.StorageEntryOmit<ExtArgs> | null
  /**
   * Filter, which StorageEntry to fetch.
   */
  where: Prisma.StorageEntryWhereUniqueInput
}

/**
 * StorageEntry findFirst
 */
export type StorageEntryFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StorageEntry
   */
  select?: Prisma.StorageEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the StorageEntry
   */
  omit?: Prisma.StorageEntryOmit<ExtArgs> | null
  /**
   * Filter, which StorageEntry to fetch.
   */
  where?: Prisma.StorageEntryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of StorageEntries to fetch.
   */
  orderBy?: Prisma.StorageEntryOrderByWithRelationInput | Prisma.StorageEntryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for StorageEntries.
   */
  cursor?: Prisma.StorageEntryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` StorageEntries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` StorageEntries.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of StorageEntries.
   */
  distinct?: Prisma.StorageEntryScalarFieldEnum | Prisma.StorageEntryScalarFieldEnum[]
}

/**
 * StorageEntry findFirstOrThrow
 */
export type StorageEntryFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StorageEntry
   */
  select?: Prisma.StorageEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the StorageEntry
   */
  omit?: Prisma.StorageEntryOmit<ExtArgs> | null
  /**
   * Filter, which StorageEntry to fetch.
   */
  where?: Prisma.StorageEntryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of StorageEntries to fetch.
   */
  orderBy?: Prisma.StorageEntryOrderByWithRelationInput | Prisma.StorageEntryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for StorageEntries.
   */
  cursor?: Prisma.StorageEntryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` StorageEntries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` StorageEntries.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of StorageEntries.
   */
  distinct?: Prisma.StorageEntryScalarFieldEnum | Prisma.StorageEntryScalarFieldEnum[]
}

/**
 * StorageEntry findMany
 */
export type StorageEntryFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StorageEntry
   */
  select?: Prisma.StorageEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the StorageEntry
   */
  omit?: Prisma.StorageEntryOmit<ExtArgs> | null
  /**
   * Filter, which StorageEntries to fetch.
   */
  where?: Prisma.StorageEntryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of StorageEntries to fetch.
   */
  orderBy?: Prisma.StorageEntryOrderByWithRelationInput | Prisma.StorageEntryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing StorageEntries.
   */
  cursor?: Prisma.StorageEntryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` StorageEntries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` StorageEntries.
   */
  skip?: number
  distinct?: Prisma.StorageEntryScalarFieldEnum | Prisma.StorageEntryScalarFieldEnum[]
}

/**
 * StorageEntry create
 */
export type StorageEntryCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StorageEntry
   */
  select?: Prisma.StorageEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the StorageEntry
   */
  omit?: Prisma.StorageEntryOmit<ExtArgs> | null
  /**
   * The data needed to create a StorageEntry.
   */
  data: Prisma.XOR<Prisma.StorageEntryCreateInput, Prisma.StorageEntryUncheckedCreateInput>
}

/**
 * StorageEntry createMany
 */
export type StorageEntryCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many StorageEntries.
   */
  data: Prisma.StorageEntryCreateManyInput | Prisma.StorageEntryCreateManyInput[]
}

/**
 * StorageEntry createManyAndReturn
 */
export type StorageEntryCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StorageEntry
   */
  select?: Prisma.StorageEntrySelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the StorageEntry
   */
  omit?: Prisma.StorageEntryOmit<ExtArgs> | null
  /**
   * The data used to create many StorageEntries.
   */
  data: Prisma.StorageEntryCreateManyInput | Prisma.StorageEntryCreateManyInput[]
}

/**
 * StorageEntry update
 */
export type StorageEntryUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StorageEntry
   */
  select?: Prisma.StorageEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the StorageEntry
   */
  omit?: Prisma.StorageEntryOmit<ExtArgs> | null
  /**
   * The data needed to update a StorageEntry.
   */
  data: Prisma.XOR<Prisma.StorageEntryUpdateInput, Prisma.StorageEntryUncheckedUpdateInput>
  /**
   * Choose, which StorageEntry to update.
   */
  where: Prisma.StorageEntryWhereUniqueInput
}

/**
 * StorageEntry updateMany
 */
export type StorageEntryUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update StorageEntries.
   */
  data: Prisma.XOR<Prisma.StorageEntryUpdateManyMutationInput, Prisma.StorageEntryUncheckedUpdateManyInput>
  /**
   * Filter which StorageEntries to update
   */
  where?: Prisma.StorageEntryWhereInput
  /**
   * Limit how many StorageEntries to update.
   */
  limit?: number
}

/**
 * StorageEntry updateManyAndReturn
 */
export type StorageEntryUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StorageEntry
   */
  select?: Prisma.StorageEntrySelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the StorageEntry
   */
  omit?: Prisma.StorageEntryOmit<ExtArgs> | null
  /**
   * The data used to update StorageEntries.
   */
  data: Prisma.XOR<Prisma.StorageEntryUpdateManyMutationInput, Prisma.StorageEntryUncheckedUpdateManyInput>
  /**
   * Filter which StorageEntries to update
   */
  where?: Prisma.StorageEntryWhereInput
  /**
   * Limit how many StorageEntries to update.
   */
  limit?: number
}

/**
 * StorageEntry upsert
 */
export type StorageEntryUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StorageEntry
   */
  select?: Prisma.StorageEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the StorageEntry
   */
  omit?: Prisma.StorageEntryOmit<ExtArgs> | null
  /**
   * The filter to search for the StorageEntry to update in case it exists.
   */
  where: Prisma.StorageEntryWhereUniqueInput
  /**
   * In case the StorageEntry found by the `where` argument doesn't exist, create a new StorageEntry with this data.
   */
  create: Prisma.XOR<Prisma.StorageEntryCreateInput, Prisma.StorageEntryUncheckedCreateInput>
  /**
   * In case the StorageEntry was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.StorageEntryUpdateInput, Prisma.StorageEntryUncheckedUpdateInput>
}

/**
 * StorageEntry delete
 */
export type StorageEntryDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StorageEntry
   */
  select?: Prisma.StorageEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the StorageEntry
   */
  omit?: Prisma.StorageEntryOmit<ExtArgs> | null
  /**
   * Filter which StorageEntry to delete.
   */
  where: Prisma.StorageEntryWhereUniqueInput
}

/**
 * StorageEntry deleteMany
 */
export type StorageEntryDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which StorageEntries to delete
   */
  where?: Prisma.StorageEntryWhereInput
  /**
   * Limit how many StorageEntries to delete.
   */
  limit?: number
}

/**
 * StorageEntry without action
 */
export type StorageEntryDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StorageEntry
   */
  select?: Prisma.StorageEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the StorageEntry
   */
  omit?: Prisma.StorageEntryOmit<ExtArgs> | null
}
