---
version: 2
plan:
  project-key: AJL
  key: HOSTLISTCMPLRBUILD
  name: hostlist-compiler - build (Deno)
variables:
  dockerContainer: denoland/deno:latest

stages:
  - Build:
      manual: false
      final: false
      jobs:
        - Build

Build:
  key: BUILD
  other:
    clean-working-dir: true
  docker:
    image: "${bamboo.dockerContainer}"
  tasks:
    - checkout:
        force-clean-build: true
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -e
            set -x

            # Fix mixed logs
            exec 2>&1

            # Read version from deno.json
            VERSION=$(deno eval "console.log(JSON.parse(Deno.readTextFileSync('./deno.json')).version)")
            
            # Write version to build.txt for injection
            mkdir -p dist
            echo "version=$VERSION" > dist/build.txt

    - inject-variables:
        file: dist/build.txt
        scope: RESULT
        namespace: inject
    - script:
        interpreter: SHELL
        scripts:
          - |-
            #!/bin/bash
            set -e
            set -x

            # Fix mixed logs
            exec 2>&1

            # Fail if version was not incremented
            if [ "$(git tag -l "v${bamboo.inject.version}")" ]; then
              echo "Build failed!"
              echo "Error: Tag v${bamboo.inject.version} already exists. Increment version before build"
              exit 1
            fi

            # Create standalone executable using deno compile
            deno compile \
              --allow-read \
              --allow-write \
              --allow-net \
              --output hostlist-compiler \
              src/cli.deno.ts

            # Create tarball with the compiled binary
            tar -czf hostlist-compiler.tar.gz hostlist-compiler
    - any-task:
        plugin-key: com.atlassian.bamboo.plugins.vcs:task.vcs.tagging
        configuration:
          selectedRepository: defaultRepository
          tagName: v${bamboo.inject.version}
  artifacts:
    - name: hostlist-compiler.tar.gz
      location: ./
      pattern: hostlist-compiler.tar.gz
      shared: true
      required: true
  requirements:
    - adg-docker: true

triggers: []

branches:
  create: manually
  delete: never
  link-to-jira: true

notifications:
  - events:
      - plan-status-changed
    recipients:
      - webhook:
          name: Build webhook
          url: http://prod.jirahub.service.eu.consul/v1/webhook/bamboo

labels: []

other:
  concurrent-build-plugin: system-default
