---
version: 2
plan:
  project-key: AJL
  key: HOSTLISTCMPLRTEST
  name: hostlist-compiler - tests (Deno)
variables:
  # Using official Deno Docker image
  dockerContainer: denoland/deno:latest

stages:
  - Test:
      manual: false
      final: false
      jobs:
        - Test

Test:
  key: TEST
  docker:
    image: "${bamboo.dockerContainer}"
  tasks:
    - checkout:
        force-clean-build: true
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -e
            set -x

            # Fix mixed logs
            exec 2>&1

            # Deno doesn't need package installation like Node.js/yarn
            # Dependencies are fetched on first run

            # Run linter
            deno lint src/

            # Run formatter check
            deno fmt --check src/

            # Run type checking
            deno check src/**/*.ts

            # Run tests
            deno test --allow-read --allow-write --allow-net
  final-tasks:
    - clean
  requirements:
    - adg-docker: true

branches:
  create: for-pull-request
  delete:
    after-deleted-days: '1'
    after-inactive-days: '5'
  link-to-jira: true

notifications:
  - events:
      - plan-status-changed
    recipients:
      - webhook:
          name: Build webhook
          url: http://prod.jirahub.service.eu.consul/v1/webhook/bamboo

labels: []
other:
  concurrent-build-plugin: system-default
