---
version: 2
plan:
  project-key: AJL
  key: HBRTSPECS
  name: hostlist-compiler - test
variables:
  dockerNode: adguard/node-ssh:14.18--0

stages:
  - Test:
      manual: 'false'
      final: 'false'
      jobs:
        - Test

Test:
  key: TEST
  docker:
    image: "${bamboo.dockerNode}"
    volumes:
      ${system.YARN_DIR}: "${bamboo.cacheYarn}"
  tasks:
    - checkout:
        force-clean-build: 'true'
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -e
            set -x
            yarn install
            yarn lint
            yarn test
            rm -rf node_modules
  final-tasks:
    - clean
  requirements:
    - adg-docker: 'true'

branches:
  create: for-pull-request
  delete:
    after-deleted-days: '1'
    after-inactive-days: '5'
  link-to-jira: 'true'

notifications:
  - events:
      - plan-status-changed
    recipients:
      - webhook:
          name: Build webhook
          url: http://prod.jirahub.service.eu.consul/v1/webhook/bamboo?channel=adguard-qa

labels: []
other:
  concurrent-build-plugin: system-default
