$kind: http-example
request:
  url: http://{{baseUrl}}/compile/async
  method: POST
  headers:
    Content-Type: application/json
    Accept: application/json
  body:
    type: json
    content: >-
      {
        "configuration": {
          "name": "string",
          "sources": [
            {
              "source": "string",
              "name": "string",
              "type": "adblock",
              "transformations": [
                "ConvertToAscii",
                "RemoveEmptyLines"
              ],
              "exclusions": [
                "string",
                "string"
              ],
              "inclusions": [
                "string",
                "string"
              ]
            }
          ],
          "description": "string",
          "homepage": "https://gnofrMBddBAKDCAx.wncteb+RFp7ObYu,U2cUrrTRsxVa0zlv9",
          "license": "string",
          "version": "string",
          "transformations": [
            "InvertAllow",
            "RemoveComments"
          ],
          "exclusions": [
            "string",
            "string"
          ],
          "exclusions_sources": [
            "string",
            "string"
          ],
          "inclusions": [
            "string",
            "string"
          ],
          "inclusions_sources": [
            "string",
            "string"
          ]
        },
        "preFetchedContent": {
          "key_0": "string",
          "key_1": "string",
          "key_2": "string"
        },
        "benchmark": false,
        "turnstileToken": "string",
        "priority": "standard"
      }
response:
  statusCode: 500
  statusText: Internal Server Error
  headers:
    Content-Type: application/json
  body:
    type: json
    content: |-
      {
        "success": false,
        "error": "string"
      }
order: 3000
