$kind: http-request
url: http://{{baseUrl}}/api/turnstile-config
method: GET
headers:
  Accept: application/json
body:
  type: text
  content: ""
examples: ./.resources/Get Turnstile configuration.resources/examples
order: 1000
